
(cl:in-package :asdf)

(defsystem "movement_utils-srv"
  :depends-on (:roslisp-msg-protocol :roslisp-utils )
  :components ((:file "_package")
    (:file "body_feedback" :depends-on ("_package_body_feedback"))
    (:file "_package_body_feedback" :depends-on ("_package"))
    (:file "enable_torque" :depends-on ("_package_enable_torque"))
    (:file "_package_enable_torque" :depends-on ("_package"))
    (:file "gait" :depends-on ("_package_gait"))
    (:file "_package_gait" :depends-on ("_package"))
    (:file "head_feedback" :depends-on ("_package_head_feedback"))
    (:file "_package_head_feedback" :depends-on ("_package"))
    (:file "page" :depends-on ("_package_page"))
    (:file "_package_page" :depends-on ("_package"))
    (:file "rotate" :depends-on ("_package_rotate"))
    (:file "_package_rotate" :depends-on ("_package"))
    (:file "walk_forward" :depends-on ("_package_walk_forward"))
    (:file "_package_walk_forward" :depends-on ("_package"))
  ))