// Generated by gencpp from file modularized_bhv_msgs/moveRequestResponse.msg
// DO NOT EDIT!


#ifndef MODULARIZED_BHV_MSGS_MESSAGE_MOVEREQUESTRESPONSE_H
#define MODULARIZED_BHV_MSGS_MESSAGE_MOVEREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace modularized_bhv_msgs
{
template <class ContainerAllocator>
struct moveRequestResponse_
{
  typedef moveRequestResponse_<ContainerAllocator> Type;

  moveRequestResponse_()
    : success(false)  {
    }
  moveRequestResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct moveRequestResponse_

typedef ::modularized_bhv_msgs::moveRequestResponse_<std::allocator<void> > moveRequestResponse;

typedef boost::shared_ptr< ::modularized_bhv_msgs::moveRequestResponse > moveRequestResponsePtr;
typedef boost::shared_ptr< ::modularized_bhv_msgs::moveRequestResponse const> moveRequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator1> & lhs, const ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator1> & lhs, const ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace modularized_bhv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "modularized_bhv_msgs/moveRequestResponse";
  }

  static const char* value(const ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveRequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::modularized_bhv_msgs::moveRequestResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODULARIZED_BHV_MSGS_MESSAGE_MOVEREQUESTRESPONSE_H
