// Generated by gencpp from file modularized_bhv_msgs/moveRequest.msg
// DO NOT EDIT!


#ifndef MODULARIZED_BHV_MSGS_MESSAGE_MOVEREQUEST_H
#define MODULARIZED_BHV_MSGS_MESSAGE_MOVEREQUEST_H

#include <ros/service_traits.h>


#include <modularized_bhv_msgs/moveRequestRequest.h>
#include <modularized_bhv_msgs/moveRequestResponse.h>


namespace modularized_bhv_msgs
{

struct moveRequest
{

typedef moveRequestRequest Request;
typedef moveRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct moveRequest
} // namespace modularized_bhv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::modularized_bhv_msgs::moveRequest > {
  static const char* value()
  {
    return "fa4c3676b8fc489dd65422b45b94f727";
  }

  static const char* value(const ::modularized_bhv_msgs::moveRequest&) { return value(); }
};

template<>
struct DataType< ::modularized_bhv_msgs::moveRequest > {
  static const char* value()
  {
    return "modularized_bhv_msgs/moveRequest";
  }

  static const char* value(const ::modularized_bhv_msgs::moveRequest&) { return value(); }
};


// service_traits::MD5Sum< ::modularized_bhv_msgs::moveRequestRequest> should match
// service_traits::MD5Sum< ::modularized_bhv_msgs::moveRequest >
template<>
struct MD5Sum< ::modularized_bhv_msgs::moveRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::modularized_bhv_msgs::moveRequest >::value();
  }
  static const char* value(const ::modularized_bhv_msgs::moveRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::modularized_bhv_msgs::moveRequestRequest> should match
// service_traits::DataType< ::modularized_bhv_msgs::moveRequest >
template<>
struct DataType< ::modularized_bhv_msgs::moveRequestRequest>
{
  static const char* value()
  {
    return DataType< ::modularized_bhv_msgs::moveRequest >::value();
  }
  static const char* value(const ::modularized_bhv_msgs::moveRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::modularized_bhv_msgs::moveRequestResponse> should match
// service_traits::MD5Sum< ::modularized_bhv_msgs::moveRequest >
template<>
struct MD5Sum< ::modularized_bhv_msgs::moveRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::modularized_bhv_msgs::moveRequest >::value();
  }
  static const char* value(const ::modularized_bhv_msgs::moveRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::modularized_bhv_msgs::moveRequestResponse> should match
// service_traits::DataType< ::modularized_bhv_msgs::moveRequest >
template<>
struct DataType< ::modularized_bhv_msgs::moveRequestResponse>
{
  static const char* value()
  {
    return DataType< ::modularized_bhv_msgs::moveRequest >::value();
  }
  static const char* value(const ::modularized_bhv_msgs::moveRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MODULARIZED_BHV_MSGS_MESSAGE_MOVEREQUEST_H
