// Generated by gencpp from file modularized_bhv_msgs/moveRequestRequest.msg
// DO NOT EDIT!


#ifndef MODULARIZED_BHV_MSGS_MESSAGE_MOVEREQUESTREQUEST_H
#define MODULARIZED_BHV_MSGS_MESSAGE_MOVEREQUESTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace modularized_bhv_msgs
{
template <class ContainerAllocator>
struct moveRequestRequest_
{
  typedef moveRequestRequest_<ContainerAllocator> Type;

  moveRequestRequest_()
    : moveRequest()  {
    }
  moveRequestRequest_(const ContainerAllocator& _alloc)
    : moveRequest(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _moveRequest_type;
  _moveRequest_type moveRequest;





  typedef boost::shared_ptr< ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct moveRequestRequest_

typedef ::modularized_bhv_msgs::moveRequestRequest_<std::allocator<void> > moveRequestRequest;

typedef boost::shared_ptr< ::modularized_bhv_msgs::moveRequestRequest > moveRequestRequestPtr;
typedef boost::shared_ptr< ::modularized_bhv_msgs::moveRequestRequest const> moveRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator1> & lhs, const ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.moveRequest == rhs.moveRequest;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator1> & lhs, const ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace modularized_bhv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b133e08dd2bfaecedf3ed6e116063474";
  }

  static const char* value(const ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb133e08dd2bfaeceULL;
  static const uint64_t static_value2 = 0xdf3ed6e116063474ULL;
};

template<class ContainerAllocator>
struct DataType< ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "modularized_bhv_msgs/moveRequestRequest";
  }

  static const char* value(const ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string moveRequest\n"
;
  }

  static const char* value(const ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.moveRequest);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::modularized_bhv_msgs::moveRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "moveRequest: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.moveRequest);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODULARIZED_BHV_MSGS_MESSAGE_MOVEREQUESTREQUEST_H
