// Generated by gencpp from file modularized_bhv_msgs/stateMachineMsg.msg
// DO NOT EDIT!


#ifndef MODULARIZED_BHV_MSGS_MESSAGE_STATEMACHINEMSG_H
#define MODULARIZED_BHV_MSGS_MESSAGE_STATEMACHINEMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace modularized_bhv_msgs
{
template <class ContainerAllocator>
struct stateMachineMsg_
{
  typedef stateMachineMsg_<ContainerAllocator> Type;

  stateMachineMsg_()
    : ballPosition()
    , ballClose(false)
    , ballFound(false)
    , fallState()
    , horMotorOutOfCenter()
    , headKickCheck(false)  {
    }
  stateMachineMsg_(const ContainerAllocator& _alloc)
    : ballPosition(_alloc)
    , ballClose(false)
    , ballFound(false)
    , fallState(_alloc)
    , horMotorOutOfCenter(_alloc)
    , headKickCheck(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ballPosition_type;
  _ballPosition_type ballPosition;

   typedef uint8_t _ballClose_type;
  _ballClose_type ballClose;

   typedef uint8_t _ballFound_type;
  _ballFound_type ballFound;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _fallState_type;
  _fallState_type fallState;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _horMotorOutOfCenter_type;
  _horMotorOutOfCenter_type horMotorOutOfCenter;

   typedef uint8_t _headKickCheck_type;
  _headKickCheck_type headKickCheck;





  typedef boost::shared_ptr< ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> const> ConstPtr;

}; // struct stateMachineMsg_

typedef ::modularized_bhv_msgs::stateMachineMsg_<std::allocator<void> > stateMachineMsg;

typedef boost::shared_ptr< ::modularized_bhv_msgs::stateMachineMsg > stateMachineMsgPtr;
typedef boost::shared_ptr< ::modularized_bhv_msgs::stateMachineMsg const> stateMachineMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator1> & lhs, const ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator2> & rhs)
{
  return lhs.ballPosition == rhs.ballPosition &&
    lhs.ballClose == rhs.ballClose &&
    lhs.ballFound == rhs.ballFound &&
    lhs.fallState == rhs.fallState &&
    lhs.horMotorOutOfCenter == rhs.horMotorOutOfCenter &&
    lhs.headKickCheck == rhs.headKickCheck;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator1> & lhs, const ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace modularized_bhv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c591d7d3c44206a23a253ed3e26e96da";
  }

  static const char* value(const ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc591d7d3c44206a2ULL;
  static const uint64_t static_value2 = 0x3a253ed3e26e96daULL;
};

template<class ContainerAllocator>
struct DataType< ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "modularized_bhv_msgs/stateMachineMsg";
  }

  static const char* value(const ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ballPosition\n"
"bool ballClose\n"
"bool ballFound\n"
"string fallState\n"
"string horMotorOutOfCenter\n"
"bool headKickCheck\n"
;
  }

  static const char* value(const ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ballPosition);
      stream.next(m.ballClose);
      stream.next(m.ballFound);
      stream.next(m.fallState);
      stream.next(m.horMotorOutOfCenter);
      stream.next(m.headKickCheck);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stateMachineMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::modularized_bhv_msgs::stateMachineMsg_<ContainerAllocator>& v)
  {
    s << indent << "ballPosition: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ballPosition);
    s << indent << "ballClose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ballClose);
    s << indent << "ballFound: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ballFound);
    s << indent << "fallState: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.fallState);
    s << indent << "horMotorOutOfCenter: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.horMotorOutOfCenter);
    s << indent << "headKickCheck: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.headKickCheck);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODULARIZED_BHV_MSGS_MESSAGE_STATEMACHINEMSG_H
