# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/pages.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mainFrame.setObjectName("mainFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftFrame = QtWidgets.QFrame(self.mainFrame)
        self.leftFrame.setMaximumSize(QtCore.QSize(320, 16777215))
        self.leftFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.leftFrame.setObjectName("leftFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.edromFrame = QtWidgets.QFrame(self.leftFrame)
        self.edromFrame.setMinimumSize(QtCore.QSize(0, 115))
        self.edromFrame.setMaximumSize(QtCore.QSize(16777215, 115))
        self.edromFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.edromFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.edromFrame.setObjectName("edromFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.edromFrame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.edromFrame)
        self.label.setMinimumSize(QtCore.QSize(113, 113))
        self.label.setMaximumSize(QtCore.QSize(113, 113))
        self.label.setStyleSheet("background-image: url(:/logo/logo.png);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logo/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.verticalLayout.addWidget(self.edromFrame)
        self.line = QtWidgets.QFrame(self.leftFrame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.motorsFrame = QtWidgets.QFrame(self.leftFrame)
        self.motorsFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.motorsFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.motorsFrame.setObjectName("motorsFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.motorsFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.torqueAllFrame = QtWidgets.QFrame(self.motorsFrame)
        self.torqueAllFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.torqueAllFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.torqueAllFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.torqueAllFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.torqueAllFrame.setObjectName("torqueAllFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.torqueAllFrame)
        self.horizontalLayout_4.setContentsMargins(4, 5, 4, 5)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.torqueButton = QtWidgets.QPushButton(self.torqueAllFrame)
        self.torqueButton.setMinimumSize(QtCore.QSize(150, 0))
        self.torqueButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.torqueButton.setDefault(False)
        self.torqueButton.setFlat(False)
        self.torqueButton.setObjectName("torqueButton")
        self.horizontalLayout_4.addWidget(self.torqueButton)
        self.verticalLayout_2.addWidget(self.torqueAllFrame)
        self.frame_8 = QtWidgets.QFrame(self.motorsFrame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollAreaMotors = QtWidgets.QScrollArea(self.frame_8)
        self.scrollAreaMotors.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollAreaMotors.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollAreaMotors.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollAreaMotors.setWidgetResizable(True)
        self.scrollAreaMotors.setObjectName("scrollAreaMotors")
        self.scrollMotorsContent = QtWidgets.QWidget()
        self.scrollMotorsContent.setGeometry(QtCore.QRect(0, 0, 304, 1920))
        self.scrollMotorsContent.setObjectName("scrollMotorsContent")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollMotorsContent)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.motor0 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor0.setMinimumSize(QtCore.QSize(0, 100))
        self.motor0.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor0.setObjectName("motor0")
        self.verticalLayout_3.addWidget(self.motor0)
        self.motor1 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor1.setMinimumSize(QtCore.QSize(0, 100))
        self.motor1.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor1.setObjectName("motor1")
        self.verticalLayout_3.addWidget(self.motor1)
        self.motor2 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor2.setMinimumSize(QtCore.QSize(0, 100))
        self.motor2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor2.setObjectName("motor2")
        self.verticalLayout_3.addWidget(self.motor2)
        self.motor3 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor3.setMinimumSize(QtCore.QSize(0, 100))
        self.motor3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor3.setObjectName("motor3")
        self.verticalLayout_3.addWidget(self.motor3)
        self.motor4 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor4.setMinimumSize(QtCore.QSize(0, 100))
        self.motor4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor4.setObjectName("motor4")
        self.verticalLayout_3.addWidget(self.motor4)
        self.motor5 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor5.setMinimumSize(QtCore.QSize(0, 100))
        self.motor5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor5.setObjectName("motor5")
        self.verticalLayout_3.addWidget(self.motor5)
        self.motor6 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor6.setMinimumSize(QtCore.QSize(0, 100))
        self.motor6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor6.setObjectName("motor6")
        self.verticalLayout_3.addWidget(self.motor6)
        self.motor7 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor7.setMinimumSize(QtCore.QSize(0, 100))
        self.motor7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor7.setObjectName("motor7")
        self.verticalLayout_3.addWidget(self.motor7)
        self.motor8 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor8.setMinimumSize(QtCore.QSize(0, 100))
        self.motor8.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor8.setObjectName("motor8")
        self.verticalLayout_3.addWidget(self.motor8)
        self.motor9 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor9.setMinimumSize(QtCore.QSize(0, 100))
        self.motor9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor9.setObjectName("motor9")
        self.verticalLayout_3.addWidget(self.motor9)
        self.motor10 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor10.setMinimumSize(QtCore.QSize(0, 100))
        self.motor10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor10.setObjectName("motor10")
        self.verticalLayout_3.addWidget(self.motor10)
        self.motor11 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor11.setMinimumSize(QtCore.QSize(0, 100))
        self.motor11.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor11.setObjectName("motor11")
        self.verticalLayout_3.addWidget(self.motor11)
        self.motor12 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor12.setMinimumSize(QtCore.QSize(0, 100))
        self.motor12.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor12.setObjectName("motor12")
        self.verticalLayout_3.addWidget(self.motor12)
        self.motor13 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor13.setMinimumSize(QtCore.QSize(0, 100))
        self.motor13.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor13.setObjectName("motor13")
        self.verticalLayout_3.addWidget(self.motor13)
        self.motor14 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor14.setMinimumSize(QtCore.QSize(0, 100))
        self.motor14.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor14.setObjectName("motor14")
        self.verticalLayout_3.addWidget(self.motor14)
        self.motor15 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor15.setMinimumSize(QtCore.QSize(0, 100))
        self.motor15.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor15.setObjectName("motor15")
        self.verticalLayout_3.addWidget(self.motor15)
        self.motor16 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor16.setMinimumSize(QtCore.QSize(0, 100))
        self.motor16.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor16.setObjectName("motor16")
        self.verticalLayout_3.addWidget(self.motor16)
        self.motor17 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor17.setMinimumSize(QtCore.QSize(0, 100))
        self.motor17.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor17.setObjectName("motor17")
        self.verticalLayout_3.addWidget(self.motor17)
        self.scrollAreaMotors.setWidget(self.scrollMotorsContent)
        self.horizontalLayout_5.addWidget(self.scrollAreaMotors)
        self.verticalLayout_2.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.motorsFrame)
        self.buttonsFrame = QtWidgets.QFrame(self.leftFrame)
        self.buttonsFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonsFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.buttonsFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buttonsFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.buttonsFrame.setObjectName("buttonsFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.buttonsFrame)
        self.horizontalLayout_3.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveCurrentPose = QtWidgets.QPushButton(self.buttonsFrame)
        self.saveCurrentPose.setMinimumSize(QtCore.QSize(0, 40))
        self.saveCurrentPose.setMaximumSize(QtCore.QSize(16777215, 40))
        self.saveCurrentPose.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/save/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveCurrentPose.setIcon(icon)
        self.saveCurrentPose.setIconSize(QtCore.QSize(25, 25))
        self.saveCurrentPose.setObjectName("saveCurrentPose")
        self.horizontalLayout_3.addWidget(self.saveCurrentPose)
        self.playFromFirst = QtWidgets.QPushButton(self.buttonsFrame)
        self.playFromFirst.setMinimumSize(QtCore.QSize(0, 40))
        self.playFromFirst.setMaximumSize(QtCore.QSize(16777215, 40))
        self.playFromFirst.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/play/playBranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playFromFirst.setIcon(icon1)
        self.playFromFirst.setIconSize(QtCore.QSize(25, 25))
        self.playFromFirst.setObjectName("playFromFirst")
        self.horizontalLayout_3.addWidget(self.playFromFirst)
        self.playFromSelected = QtWidgets.QPushButton(self.buttonsFrame)
        self.playFromSelected.setMinimumSize(QtCore.QSize(0, 40))
        self.playFromSelected.setMaximumSize(QtCore.QSize(16777215, 40))
        self.playFromSelected.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/play2/play2Branco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playFromSelected.setIcon(icon2)
        self.playFromSelected.setIconSize(QtCore.QSize(25, 25))
        self.playFromSelected.setObjectName("playFromSelected")
        self.horizontalLayout_3.addWidget(self.playFromSelected)
        self.verticalLayout.addWidget(self.buttonsFrame)
        self.horizontalLayout_2.addWidget(self.leftFrame)
        self.rightFrame = QtWidgets.QFrame(self.mainFrame)
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.rightFrame)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.idsFrame = QtWidgets.QFrame(self.rightFrame)
        self.idsFrame.setMinimumSize(QtCore.QSize(30, 0))
        self.idsFrame.setMaximumSize(QtCore.QSize(30, 16777215))
        self.idsFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.idsFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.idsFrame.setObjectName("idsFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.idsFrame)
        self.verticalLayout_4.setContentsMargins(0, 1, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line_24 = QtWidgets.QFrame(self.idsFrame)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.verticalLayout_4.addWidget(self.line_24)
        self.label_2 = QtWidgets.QLabel(self.idsFrame)
        self.label_2.setMinimumSize(QtCore.QSize(10, 10))
        self.label_2.setMaximumSize(QtCore.QSize(50, 50))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.line_2 = QtWidgets.QFrame(self.idsFrame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.label_3 = QtWidgets.QLabel(self.idsFrame)
        self.label_3.setMinimumSize(QtCore.QSize(10, 10))
        self.label_3.setMaximumSize(QtCore.QSize(50, 50))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.line_3 = QtWidgets.QFrame(self.idsFrame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.label_5 = QtWidgets.QLabel(self.idsFrame)
        self.label_5.setMinimumSize(QtCore.QSize(10, 10))
        self.label_5.setMaximumSize(QtCore.QSize(50, 50))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.line_4 = QtWidgets.QFrame(self.idsFrame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.label_4 = QtWidgets.QLabel(self.idsFrame)
        self.label_4.setMinimumSize(QtCore.QSize(10, 10))
        self.label_4.setMaximumSize(QtCore.QSize(50, 50))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.line_5 = QtWidgets.QFrame(self.idsFrame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        self.label_83 = QtWidgets.QLabel(self.idsFrame)
        self.label_83.setMinimumSize(QtCore.QSize(10, 10))
        self.label_83.setMaximumSize(QtCore.QSize(50, 50))
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.verticalLayout_4.addWidget(self.label_83)
        self.line_6 = QtWidgets.QFrame(self.idsFrame)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_4.addWidget(self.line_6)
        self.label_82 = QtWidgets.QLabel(self.idsFrame)
        self.label_82.setMinimumSize(QtCore.QSize(10, 10))
        self.label_82.setMaximumSize(QtCore.QSize(50, 50))
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.verticalLayout_4.addWidget(self.label_82)
        self.line_7 = QtWidgets.QFrame(self.idsFrame)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_4.addWidget(self.line_7)
        self.label_85 = QtWidgets.QLabel(self.idsFrame)
        self.label_85.setMinimumSize(QtCore.QSize(10, 10))
        self.label_85.setMaximumSize(QtCore.QSize(50, 50))
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_4.addWidget(self.label_85)
        self.line_8 = QtWidgets.QFrame(self.idsFrame)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_4.addWidget(self.line_8)
        self.label_84 = QtWidgets.QLabel(self.idsFrame)
        self.label_84.setMinimumSize(QtCore.QSize(10, 10))
        self.label_84.setMaximumSize(QtCore.QSize(50, 50))
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_4.addWidget(self.label_84)
        self.line_9 = QtWidgets.QFrame(self.idsFrame)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_4.addWidget(self.line_9)
        self.label_98 = QtWidgets.QLabel(self.idsFrame)
        self.label_98.setMinimumSize(QtCore.QSize(10, 10))
        self.label_98.setMaximumSize(QtCore.QSize(50, 50))
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName("label_98")
        self.verticalLayout_4.addWidget(self.label_98)
        self.line_10 = QtWidgets.QFrame(self.idsFrame)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_4.addWidget(self.line_10)
        self.label_89 = QtWidgets.QLabel(self.idsFrame)
        self.label_89.setMinimumSize(QtCore.QSize(10, 10))
        self.label_89.setMaximumSize(QtCore.QSize(50, 50))
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setObjectName("label_89")
        self.verticalLayout_4.addWidget(self.label_89)
        self.line_11 = QtWidgets.QFrame(self.idsFrame)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_4.addWidget(self.line_11)
        self.label_86 = QtWidgets.QLabel(self.idsFrame)
        self.label_86.setMinimumSize(QtCore.QSize(10, 10))
        self.label_86.setMaximumSize(QtCore.QSize(50, 50))
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_4.addWidget(self.label_86)
        self.line_12 = QtWidgets.QFrame(self.idsFrame)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_4.addWidget(self.line_12)
        self.label_91 = QtWidgets.QLabel(self.idsFrame)
        self.label_91.setMinimumSize(QtCore.QSize(10, 10))
        self.label_91.setMaximumSize(QtCore.QSize(50, 50))
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.verticalLayout_4.addWidget(self.label_91)
        self.line_13 = QtWidgets.QFrame(self.idsFrame)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_4.addWidget(self.line_13)
        self.label_87 = QtWidgets.QLabel(self.idsFrame)
        self.label_87.setMinimumSize(QtCore.QSize(10, 10))
        self.label_87.setMaximumSize(QtCore.QSize(50, 50))
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName("label_87")
        self.verticalLayout_4.addWidget(self.label_87)
        self.line_14 = QtWidgets.QFrame(self.idsFrame)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_4.addWidget(self.line_14)
        self.label_97 = QtWidgets.QLabel(self.idsFrame)
        self.label_97.setMinimumSize(QtCore.QSize(10, 10))
        self.label_97.setMaximumSize(QtCore.QSize(50, 50))
        self.label_97.setAlignment(QtCore.Qt.AlignCenter)
        self.label_97.setObjectName("label_97")
        self.verticalLayout_4.addWidget(self.label_97)
        self.line_15 = QtWidgets.QFrame(self.idsFrame)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_4.addWidget(self.line_15)
        self.label_96 = QtWidgets.QLabel(self.idsFrame)
        self.label_96.setMinimumSize(QtCore.QSize(10, 10))
        self.label_96.setMaximumSize(QtCore.QSize(50, 50))
        self.label_96.setAlignment(QtCore.Qt.AlignCenter)
        self.label_96.setObjectName("label_96")
        self.verticalLayout_4.addWidget(self.label_96)
        self.line_16 = QtWidgets.QFrame(self.idsFrame)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_4.addWidget(self.line_16)
        self.label_88 = QtWidgets.QLabel(self.idsFrame)
        self.label_88.setMinimumSize(QtCore.QSize(10, 10))
        self.label_88.setMaximumSize(QtCore.QSize(50, 50))
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName("label_88")
        self.verticalLayout_4.addWidget(self.label_88)
        self.line_17 = QtWidgets.QFrame(self.idsFrame)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.verticalLayout_4.addWidget(self.line_17)
        self.label_92 = QtWidgets.QLabel(self.idsFrame)
        self.label_92.setMinimumSize(QtCore.QSize(10, 10))
        self.label_92.setMaximumSize(QtCore.QSize(50, 50))
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.verticalLayout_4.addWidget(self.label_92)
        self.line_18 = QtWidgets.QFrame(self.idsFrame)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.verticalLayout_4.addWidget(self.line_18)
        self.label_90 = QtWidgets.QLabel(self.idsFrame)
        self.label_90.setMinimumSize(QtCore.QSize(10, 10))
        self.label_90.setMaximumSize(QtCore.QSize(50, 50))
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setObjectName("label_90")
        self.verticalLayout_4.addWidget(self.label_90)
        self.line_19 = QtWidgets.QFrame(self.idsFrame)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.verticalLayout_4.addWidget(self.line_19)
        self.label_94 = QtWidgets.QLabel(self.idsFrame)
        self.label_94.setMinimumSize(QtCore.QSize(10, 10))
        self.label_94.setMaximumSize(QtCore.QSize(50, 50))
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_4.addWidget(self.label_94)
        self.line_20 = QtWidgets.QFrame(self.idsFrame)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.verticalLayout_4.addWidget(self.line_20)
        spacerItem = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_6.addWidget(self.idsFrame)
        self.poseScroll = QtWidgets.QScrollArea(self.rightFrame)
        self.poseScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.poseScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.poseScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.poseScroll.setWidgetResizable(True)
        self.poseScroll.setObjectName("poseScroll")
        self.poseScrollArea = QtWidgets.QWidget()
        self.poseScrollArea.setGeometry(QtCore.QRect(0, 0, 910, 664))
        self.poseScrollArea.setObjectName("poseScrollArea")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.poseScrollArea)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.poseScroll.setWidget(self.poseScrollArea)
        self.horizontalLayout_6.addWidget(self.poseScroll)
        self.horizontalLayout_2.addWidget(self.rightFrame)
        self.horizontalLayout.addWidget(self.mainFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRecent_Mov = QtWidgets.QMenu(self.menuFile)
        self.menuRecent_Mov.setObjectName("menuRecent_Mov")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionNewPage = QtWidgets.QAction(MainWindow)
        self.actionNewPage.setObjectName("actionNewPage")
        self.actionOpenPage = QtWidgets.QAction(MainWindow)
        self.actionOpenPage.setObjectName("actionOpenPage")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionShortcutsInfo = QtWidgets.QAction(MainWindow)
        self.actionShortcutsInfo.setObjectName("actionShortcutsInfo")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPlayFromStart = QtWidgets.QAction(MainWindow)
        self.actionPlayFromStart.setObjectName("actionPlayFromStart")
        self.actionPlayFromSelected = QtWidgets.QAction(MainWindow)
        self.actionPlayFromSelected.setObjectName("actionPlayFromSelected")
        self.menuFile.addAction(self.actionNewPage)
        self.menuFile.addAction(self.actionOpenPage)
        self.menuFile.addAction(self.menuRecent_Mov.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionShortcutsInfo)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.torqueButton.setText(_translate("MainWindow", "Torque On/Off"))
        self.motor0.setText(_translate("MainWindow", "Motor 0\n"
"Mínima:\n"
"Máxima:"))
        self.motor1.setText(_translate("MainWindow", "Motor 1\n"
"Mínima:\n"
"Máxima:"))
        self.motor2.setText(_translate("MainWindow", "Motor 2\n"
"Mínima:\n"
"Máxima:"))
        self.motor3.setText(_translate("MainWindow", "Motor 3\n"
"Mínima:\n"
"Máxima:"))
        self.motor4.setText(_translate("MainWindow", "Motor 4\n"
"Mínima:\n"
"Máxima:"))
        self.motor5.setText(_translate("MainWindow", "Motor 5\n"
"Mínima:\n"
"Máxima:"))
        self.motor6.setText(_translate("MainWindow", "Motor 6\n"
"Mínima:\n"
"Máxima:"))
        self.motor7.setText(_translate("MainWindow", "Motor 7\n"
"Mínima:\n"
"Máxima:"))
        self.motor8.setText(_translate("MainWindow", "Motor 8\n"
"Mínima:\n"
"Máxima:"))
        self.motor9.setText(_translate("MainWindow", "Motor 9\n"
"Mínima:\n"
"Máxima:"))
        self.motor10.setText(_translate("MainWindow", "Motor 10\n"
"Mínima:\n"
"Máxima:"))
        self.motor11.setText(_translate("MainWindow", "Motor 11\n"
"Mínima:\n"
"Máxima:"))
        self.motor12.setText(_translate("MainWindow", "Motor 12\n"
"Mínima:\n"
"Máxima:"))
        self.motor13.setText(_translate("MainWindow", "Motor 13\n"
"Mínima:\n"
"Máxima:"))
        self.motor14.setText(_translate("MainWindow", "Motor 14\n"
"Mínima:\n"
"Máxima:"))
        self.motor15.setText(_translate("MainWindow", "Motor 15\n"
"Mínima:\n"
"Máxima:"))
        self.motor16.setText(_translate("MainWindow", "Motor 16\n"
"Mínima:\n"
"Máxima:"))
        self.motor17.setText(_translate("MainWindow", "Motor 17\n"
"Mínima:\n"
"Máxima:"))
        self.label_2.setText(_translate("MainWindow", "IDs"))
        self.label_3.setText(_translate("MainWindow", "0 "))
        self.label_5.setText(_translate("MainWindow", "1 "))
        self.label_4.setText(_translate("MainWindow", "2 "))
        self.label_83.setText(_translate("MainWindow", "3 "))
        self.label_82.setText(_translate("MainWindow", "4 "))
        self.label_85.setText(_translate("MainWindow", "5 "))
        self.label_84.setText(_translate("MainWindow", "6 "))
        self.label_98.setText(_translate("MainWindow", "7 "))
        self.label_89.setText(_translate("MainWindow", "8 "))
        self.label_86.setText(_translate("MainWindow", "9 "))
        self.label_91.setText(_translate("MainWindow", "10 "))
        self.label_87.setText(_translate("MainWindow", "11 "))
        self.label_97.setText(_translate("MainWindow", "12 "))
        self.label_96.setText(_translate("MainWindow", "13 "))
        self.label_88.setText(_translate("MainWindow", "14 "))
        self.label_92.setText(_translate("MainWindow", "15 "))
        self.label_90.setText(_translate("MainWindow", "16 "))
        self.label_94.setText(_translate("MainWindow", "17 "))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuRecent_Mov.setTitle(_translate("MainWindow", "Recent Mov"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNewPage.setText(_translate("MainWindow", "New... "))
        self.actionNewPage.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpenPage.setText(_translate("MainWindow", "Open..."))
        self.actionOpenPage.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save..."))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save As..."))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionHelp.setText(_translate("MainWindow", "Edrom Help..."))
        self.actionShortcutsInfo.setText(_translate("MainWindow", "Shortcuts info"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionPlayFromStart.setText(_translate("MainWindow", "Play from start"))
        self.actionPlayFromStart.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionPlayFromSelected.setText(_translate("MainWindow", "Play From Selected"))
        self.actionPlayFromSelected.setShortcut(_translate("MainWindow", "Ctrl+Shift+P"))
import edrom_logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
