<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>bhv_independent_simulator</name>
  <version>0.0.0</version>
  <description>The bhv_independent_simulator package</description>

  <maintainer email="kirlin@todo.todo">kirlin</maintainer>
  <license>TODO</license>

  <!-- Dependências para ROS2 e Webots -->
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>webots_ros2_core</depend>
  <depend>webots_ros2_driver</depend>

  <!-- Dependências de build -->
  <buildtool_depend>ament_python</buildtool_depend>
  
  <!-- Test dependencies (opcional) -->
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>