# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from modularized_bhv_msgs/stateMachineMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class stateMachineMsg(genpy.Message):
  _md5sum = "c591d7d3c44206a23a253ed3e26e96da"
  _type = "modularized_bhv_msgs/stateMachineMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string ballPosition
bool ballClose
bool ballFound
string fallState
string horMotorOutOfCenter
bool headKickCheck"""
  __slots__ = ['ballPosition','ballClose','ballFound','fallState','horMotorOutOfCenter','headKickCheck']
  _slot_types = ['string','bool','bool','string','string','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ballPosition,ballClose,ballFound,fallState,horMotorOutOfCenter,headKickCheck

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(stateMachineMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ballPosition is None:
        self.ballPosition = ''
      if self.ballClose is None:
        self.ballClose = False
      if self.ballFound is None:
        self.ballFound = False
      if self.fallState is None:
        self.fallState = ''
      if self.horMotorOutOfCenter is None:
        self.horMotorOutOfCenter = ''
      if self.headKickCheck is None:
        self.headKickCheck = False
    else:
      self.ballPosition = ''
      self.ballClose = False
      self.ballFound = False
      self.fallState = ''
      self.horMotorOutOfCenter = ''
      self.headKickCheck = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.ballPosition
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B().pack(_x.ballClose, _x.ballFound))
      _x = self.fallState
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.horMotorOutOfCenter
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.headKickCheck
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ballPosition = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ballPosition = str[start:end]
      _x = self
      start = end
      end += 2
      (_x.ballClose, _x.ballFound,) = _get_struct_2B().unpack(str[start:end])
      self.ballClose = bool(self.ballClose)
      self.ballFound = bool(self.ballFound)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.fallState = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.fallState = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.horMotorOutOfCenter = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.horMotorOutOfCenter = str[start:end]
      start = end
      end += 1
      (self.headKickCheck,) = _get_struct_B().unpack(str[start:end])
      self.headKickCheck = bool(self.headKickCheck)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.ballPosition
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B().pack(_x.ballClose, _x.ballFound))
      _x = self.fallState
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.horMotorOutOfCenter
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.headKickCheck
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ballPosition = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ballPosition = str[start:end]
      _x = self
      start = end
      end += 2
      (_x.ballClose, _x.ballFound,) = _get_struct_2B().unpack(str[start:end])
      self.ballClose = bool(self.ballClose)
      self.ballFound = bool(self.ballFound)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.fallState = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.fallState = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.horMotorOutOfCenter = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.horMotorOutOfCenter = str[start:end]
      start = end
      end += 1
      (self.headKickCheck,) = _get_struct_B().unpack(str[start:end])
      self.headKickCheck = bool(self.headKickCheck)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
