(cl:defpackage movement_msgs-msg
  (:use )
  (:export
   "<APPROVEDMOVEMENTMSG>"
   "APPROVEDMOVEMENTMSG"
   "<HEADPARAMSMSG>"
   "HEADPARAMSMSG"
   "<OPENCMREQUESTMSG>"
   "OPENCMREQUESTMSG"
   "<OPENCMRESPONSEMSG>"
   "OPENCMRESPONSEMSG"
   "<WALKCREATORREQUESTMSG>"
   "WALKCREATORREQUESTMSG"
   "<WALKINGPOSITIONSMSG>"
   "WALKINGPOSITIONSMSG"
   "<WEBOTSREQUESTMSG>"
   "WEBOTSREQUESTMSG"
  ))

