# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pages_andamento.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        Form.setMinimumSize(QtCore.QSize(1280, 720))
        Form.setMaximumSize(QtCore.QSize(1280, 720))
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(10, 0, 241, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 150, 241, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.torqueButton = QtWidgets.QPushButton(self.frame)
        self.torqueButton.setGeometry(QtCore.QRect(40, 0, 150, 41))
        self.torqueButton.setMinimumSize(QtCore.QSize(150, 0))
        self.torqueButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.torqueButton.setDefault(False)
        self.torqueButton.setFlat(False)
        self.torqueButton.setObjectName("torqueButton")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 40, 241, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 200, 241, 481))
        self.widget.setObjectName("widget")
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 250, 161, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setGeometry(QtCore.QRect(40, 10, 161, 31))
        self.textEdit.setObjectName("textEdit")
        self.scrollAreaMotors = QtWidgets.QScrollArea(self.widget)
        self.scrollAreaMotors.setGeometry(QtCore.QRect(30, 50, 191, 181))
        self.scrollAreaMotors.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollAreaMotors.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollAreaMotors.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollAreaMotors.setWidgetResizable(True)
        self.scrollAreaMotors.setObjectName("scrollAreaMotors")
        self.scrollMotorsContent = QtWidgets.QWidget()
        self.scrollMotorsContent.setGeometry(QtCore.QRect(0, 0, 174, 667))
        self.scrollMotorsContent.setObjectName("scrollMotorsContent")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollMotorsContent)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.motor1 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor1.setMinimumSize(QtCore.QSize(0, 100))
        self.motor1.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor1.setObjectName("motor1")
        self.verticalLayout_3.addWidget(self.motor1)
        self.motor0 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor0.setMinimumSize(QtCore.QSize(0, 100))
        self.motor0.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor0.setObjectName("motor0")
        self.verticalLayout_3.addWidget(self.motor0)
        self.motor2 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor2.setMinimumSize(QtCore.QSize(0, 100))
        self.motor2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor2.setObjectName("motor2")
        self.verticalLayout_3.addWidget(self.motor2)
        self.motor3 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor3.setMinimumSize(QtCore.QSize(0, 100))
        self.motor3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor3.setObjectName("motor3")
        self.verticalLayout_3.addWidget(self.motor3)
        self.motor4 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor4.setMinimumSize(QtCore.QSize(0, 100))
        self.motor4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor4.setObjectName("motor4")
        self.verticalLayout_3.addWidget(self.motor4)
        self.motor5 = QtWidgets.QPushButton(self.scrollMotorsContent)
        self.motor5.setMinimumSize(QtCore.QSize(0, 100))
        self.motor5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor5.setObjectName("motor5")
        self.verticalLayout_3.addWidget(self.motor5)
        self.label_2 = QtWidgets.QLabel(self.scrollMotorsContent)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Downloads/Imagem do WhatsApp de 2024-04-10 à(s) 19.15.31_0a21bc07.jpg"))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.scrollAreaMotors.setWidget(self.scrollMotorsContent)
        self.scrollAreaMotors_2 = QtWidgets.QScrollArea(self.widget)
        self.scrollAreaMotors_2.setGeometry(QtCore.QRect(30, 290, 191, 181))
        self.scrollAreaMotors_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollAreaMotors_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollAreaMotors_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollAreaMotors_2.setWidgetResizable(True)
        self.scrollAreaMotors_2.setObjectName("scrollAreaMotors_2")
        self.scrollMotorsContent_2 = QtWidgets.QWidget()
        self.scrollMotorsContent_2.setGeometry(QtCore.QRect(0, 0, 174, 860))
        self.scrollMotorsContent_2.setObjectName("scrollMotorsContent_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollMotorsContent_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.motor6 = QtWidgets.QPushButton(self.scrollMotorsContent_2)
        self.motor6.setMinimumSize(QtCore.QSize(0, 100))
        self.motor6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor6.setObjectName("motor6")
        self.verticalLayout_4.addWidget(self.motor6)
        self.motor7 = QtWidgets.QPushButton(self.scrollMotorsContent_2)
        self.motor7.setMinimumSize(QtCore.QSize(0, 100))
        self.motor7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor7.setObjectName("motor7")
        self.verticalLayout_4.addWidget(self.motor7)
        self.motor8 = QtWidgets.QPushButton(self.scrollMotorsContent_2)
        self.motor8.setMinimumSize(QtCore.QSize(0, 100))
        self.motor8.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor8.setObjectName("motor8")
        self.verticalLayout_4.addWidget(self.motor8)
        self.motor9 = QtWidgets.QPushButton(self.scrollMotorsContent_2)
        self.motor9.setMinimumSize(QtCore.QSize(0, 100))
        self.motor9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor9.setObjectName("motor9")
        self.verticalLayout_4.addWidget(self.motor9)
        self.motor10 = QtWidgets.QPushButton(self.scrollMotorsContent_2)
        self.motor10.setMinimumSize(QtCore.QSize(0, 100))
        self.motor10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor10.setObjectName("motor10")
        self.verticalLayout_4.addWidget(self.motor10)
        self.motor11 = QtWidgets.QPushButton(self.scrollMotorsContent_2)
        self.motor11.setMinimumSize(QtCore.QSize(0, 100))
        self.motor11.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor11.setObjectName("motor11")
        self.verticalLayout_4.addWidget(self.motor11)
        self.motor12 = QtWidgets.QPushButton(self.scrollMotorsContent_2)
        self.motor12.setMinimumSize(QtCore.QSize(0, 100))
        self.motor12.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor12.setObjectName("motor12")
        self.verticalLayout_4.addWidget(self.motor12)
        self.motor13 = QtWidgets.QPushButton(self.scrollMotorsContent_2)
        self.motor13.setMinimumSize(QtCore.QSize(0, 100))
        self.motor13.setMaximumSize(QtCore.QSize(16777215, 100))
        self.motor13.setObjectName("motor13")
        self.verticalLayout_4.addWidget(self.motor13)
        self.scrollAreaMotors_2.setWidget(self.scrollMotorsContent_2)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 40, 113, 113))
        self.label.setMinimumSize(QtCore.QSize(113, 113))
        self.label.setMaximumSize(QtCore.QSize(113, 113))
        self.label.setStyleSheet("background-image: url(:/logo/logo.png);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logo/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.buttonsFrame = QtWidgets.QFrame(Form)
        self.buttonsFrame.setGeometry(QtCore.QRect(10, 670, 241, 50))
        self.buttonsFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonsFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.buttonsFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buttonsFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.buttonsFrame.setObjectName("buttonsFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.buttonsFrame)
        self.horizontalLayout_3.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveCurrentPose_2 = QtWidgets.QPushButton(self.buttonsFrame)
        self.saveCurrentPose_2.setMinimumSize(QtCore.QSize(0, 40))
        self.saveCurrentPose_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.saveCurrentPose_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("salvar-arquivo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveCurrentPose_2.setIcon(icon)
        self.saveCurrentPose_2.setIconSize(QtCore.QSize(25, 25))
        self.saveCurrentPose_2.setObjectName("saveCurrentPose_2")
        self.horizontalLayout_3.addWidget(self.saveCurrentPose_2)
        self.playFromFirst = QtWidgets.QPushButton(self.buttonsFrame)
        self.playFromFirst.setMinimumSize(QtCore.QSize(0, 40))
        self.playFromFirst.setMaximumSize(QtCore.QSize(16777215, 40))
        self.playFromFirst.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("botao-play (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playFromFirst.setIcon(icon1)
        self.playFromFirst.setIconSize(QtCore.QSize(25, 25))
        self.playFromFirst.setObjectName("playFromFirst")
        self.horizontalLayout_3.addWidget(self.playFromFirst)
        self.playFromSelected = QtWidgets.QPushButton(self.buttonsFrame)
        self.playFromSelected.setMinimumSize(QtCore.QSize(0, 40))
        self.playFromSelected.setMaximumSize(QtCore.QSize(16777215, 40))
        self.playFromSelected.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("proximo-botao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playFromSelected.setIcon(icon2)
        self.playFromSelected.setIconSize(QtCore.QSize(25, 25))
        self.playFromSelected.setObjectName("playFromSelected")
        self.horizontalLayout_3.addWidget(self.playFromSelected)
        self.rightFrame = QtWidgets.QFrame(Form)
        self.rightFrame.setGeometry(QtCore.QRect(250, 10, 960, 699))
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.rightFrame)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.poseScroll = QtWidgets.QScrollArea(self.rightFrame)
        self.poseScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.poseScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.poseScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.poseScroll.setWidgetResizable(True)
        self.poseScroll.setObjectName("poseScroll")
        self.poseScrollArea = QtWidgets.QWidget()
        self.poseScrollArea.setGeometry(QtCore.QRect(0, 0, 940, 662))
        self.poseScrollArea.setObjectName("poseScrollArea")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.poseScrollArea)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.poseScroll.setWidget(self.poseScrollArea)
        self.horizontalLayout_6.addWidget(self.poseScroll)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">Pages Creator</span></p></body></html>"))
        self.torqueButton.setText(_translate("Form", "Torque On/Off"))
        self.textEdit_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#00007f;\">Atuadores</span></p></body></html>"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#00007f;\">Motores</span></p></body></html>"))
        self.motor1.setText(_translate("Form", "Motor 1\n"
"Mínima:\n"
"Máxima:"))
        self.motor0.setText(_translate("Form", "Motor 0\n"
"Mínima:\n"
"Máxima:"))
        self.motor2.setText(_translate("Form", "Motor 2\n"
"Mínima:\n"
"Máxima:"))
        self.motor3.setText(_translate("Form", "Motor 3\n"
"Mínima:\n"
"Máxima:"))
        self.motor4.setText(_translate("Form", "Motor 4\n"
"Mínima:\n"
"Máxima:"))
        self.motor5.setText(_translate("Form", "Motor 5\n"
"Mínima:\n"
"Máxima:"))
        self.motor6.setText(_translate("Form", "Atuador 6\n"
"Mínima:\n"
"Máxima:"))
        self.motor7.setText(_translate("Form", "Atuador 7\n"
"Mínima:\n"
"Máxima:"))
        self.motor8.setText(_translate("Form", "Atuador 8\n"
"Mínima:\n"
"Máxima:"))
        self.motor9.setText(_translate("Form", "Atuador 9\n"
"Mínima:\n"
"Máxima:"))
        self.motor10.setText(_translate("Form", "Atuador 10\n"
"Mínima:\n"
"Máxima:"))
        self.motor11.setText(_translate("Form", "Atuador 11\n"
"Mínima:\n"
"Máxima:"))
        self.motor12.setText(_translate("Form", "Atuador 12\n"
"Mínima:\n"
"Máxima:"))
        self.motor13.setText(_translate("Form", "Atuador 13\n"
"Mínima:\n"
"Máxima:"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
