# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from movement_msgs/OpencmResponseMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class OpencmResponseMsg(genpy.Message):
  _md5sum = "f292bdc80699153415d4562d7f08a5e4"
  _type = "movement_msgs/OpencmResponseMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16[20] motors_position
int16[20] motors_velocity
"""
  __slots__ = ['motors_position','motors_velocity']
  _slot_types = ['int16[20]','int16[20]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motors_position,motors_velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OpencmResponseMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.motors_position is None:
        self.motors_position = [0] * 20
      if self.motors_velocity is None:
        self.motors_velocity = [0] * 20
    else:
      self.motors_position = [0] * 20
      self.motors_velocity = [0] * 20

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_20h().pack(*self.motors_position))
      buff.write(_get_struct_20h().pack(*self.motors_velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 40
      self.motors_position = _get_struct_20h().unpack(str[start:end])
      start = end
      end += 40
      self.motors_velocity = _get_struct_20h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.motors_position.tostring())
      buff.write(self.motors_velocity.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 40
      self.motors_position = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=20)
      start = end
      end += 40
      self.motors_velocity = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=20)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_20h = None
def _get_struct_20h():
    global _struct_20h
    if _struct_20h is None:
        _struct_20h = struct.Struct("<20h")
    return _struct_20h
