// Generated by gencpp from file movement_msgs/BehRequestSrvResponse.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_BEHREQUESTSRVRESPONSE_H
#define MOVEMENT_MSGS_MESSAGE_BEHREQUESTSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_msgs
{
template <class ContainerAllocator>
struct BehRequestSrvResponse_
{
  typedef BehRequestSrvResponse_<ContainerAllocator> Type;

  BehRequestSrvResponse_()
    : response(false)  {
    }
  BehRequestSrvResponse_(const ContainerAllocator& _alloc)
    : response(false)  {
  (void)_alloc;
    }



   typedef uint8_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BehRequestSrvResponse_

typedef ::movement_msgs::BehRequestSrvResponse_<std::allocator<void> > BehRequestSrvResponse;

typedef boost::shared_ptr< ::movement_msgs::BehRequestSrvResponse > BehRequestSrvResponsePtr;
typedef boost::shared_ptr< ::movement_msgs::BehRequestSrvResponse const> BehRequestSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator1> & lhs, const ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator1> & lhs, const ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "003b81baa95ab323fc1ddf3c7d0bee81";
  }

  static const char* value(const ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x003b81baa95ab323ULL;
  static const uint64_t static_value2 = 0xfc1ddf3c7d0bee81ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/BehRequestSrvResponse";
  }

  static const char* value(const ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool response\n"
"\n"
;
  }

  static const char* value(const ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BehRequestSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_msgs::BehRequestSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_BEHREQUESTSRVRESPONSE_H
