// Generated by gencpp from file movement_msgs/CommandToOpenCMSrvRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_COMMANDTOOPENCMSRVREQUEST_H
#define MOVEMENT_MSGS_MESSAGE_COMMANDTOOPENCMSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_msgs
{
template <class ContainerAllocator>
struct CommandToOpenCMSrvRequest_
{
  typedef CommandToOpenCMSrvRequest_<ContainerAllocator> Type;

  CommandToOpenCMSrvRequest_()
    : opencm_command()  {
    }
  CommandToOpenCMSrvRequest_(const ContainerAllocator& _alloc)
    : opencm_command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _opencm_command_type;
  _opencm_command_type opencm_command;





  typedef boost::shared_ptr< ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CommandToOpenCMSrvRequest_

typedef ::movement_msgs::CommandToOpenCMSrvRequest_<std::allocator<void> > CommandToOpenCMSrvRequest;

typedef boost::shared_ptr< ::movement_msgs::CommandToOpenCMSrvRequest > CommandToOpenCMSrvRequestPtr;
typedef boost::shared_ptr< ::movement_msgs::CommandToOpenCMSrvRequest const> CommandToOpenCMSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator1> & lhs, const ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.opencm_command == rhs.opencm_command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator1> & lhs, const ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "667104249a6d6bc22799056893a3d6dd";
  }

  static const char* value(const ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x667104249a6d6bc2ULL;
  static const uint64_t static_value2 = 0x2799056893a3d6ddULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/CommandToOpenCMSrvRequest";
  }

  static const char* value(const ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string opencm_command\n"
;
  }

  static const char* value(const ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.opencm_command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandToOpenCMSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_msgs::CommandToOpenCMSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "opencm_command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.opencm_command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_COMMANDTOOPENCMSRVREQUEST_H
