// Generated by gencpp from file movement_msgs/CommandToOpenCMSrvResponse.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_COMMANDTOOPENCMSRVRESPONSE_H
#define MOVEMENT_MSGS_MESSAGE_COMMANDTOOPENCMSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_msgs
{
template <class ContainerAllocator>
struct CommandToOpenCMSrvResponse_
{
  typedef CommandToOpenCMSrvResponse_<ContainerAllocator> Type;

  CommandToOpenCMSrvResponse_()
    : command_executed(false)  {
    }
  CommandToOpenCMSrvResponse_(const ContainerAllocator& _alloc)
    : command_executed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _command_executed_type;
  _command_executed_type command_executed;





  typedef boost::shared_ptr< ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommandToOpenCMSrvResponse_

typedef ::movement_msgs::CommandToOpenCMSrvResponse_<std::allocator<void> > CommandToOpenCMSrvResponse;

typedef boost::shared_ptr< ::movement_msgs::CommandToOpenCMSrvResponse > CommandToOpenCMSrvResponsePtr;
typedef boost::shared_ptr< ::movement_msgs::CommandToOpenCMSrvResponse const> CommandToOpenCMSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator1> & lhs, const ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.command_executed == rhs.command_executed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator1> & lhs, const ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84201e3713d34186a0242b6cb5f84aab";
  }

  static const char* value(const ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84201e3713d34186ULL;
  static const uint64_t static_value2 = 0xa0242b6cb5f84aabULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/CommandToOpenCMSrvResponse";
  }

  static const char* value(const ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool command_executed\n"
;
  }

  static const char* value(const ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command_executed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandToOpenCMSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_msgs::CommandToOpenCMSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "command_executed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command_executed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_COMMANDTOOPENCMSRVRESPONSE_H
