// Generated by gencpp from file movement_msgs/HeadParamsMsg.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_HEADPARAMSMSG_H
#define MOVEMENT_MSGS_MESSAGE_HEADPARAMSMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_msgs
{
template <class ContainerAllocator>
struct HeadParamsMsg_
{
  typedef HeadParamsMsg_<ContainerAllocator> Type;

  HeadParamsMsg_()
    : direction()
    , pattern()  {
    }
  HeadParamsMsg_(const ContainerAllocator& _alloc)
    : direction(_alloc)
    , pattern(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _direction_type;
  _direction_type direction;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pattern_type;
  _pattern_type pattern;





  typedef boost::shared_ptr< ::movement_msgs::HeadParamsMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::HeadParamsMsg_<ContainerAllocator> const> ConstPtr;

}; // struct HeadParamsMsg_

typedef ::movement_msgs::HeadParamsMsg_<std::allocator<void> > HeadParamsMsg;

typedef boost::shared_ptr< ::movement_msgs::HeadParamsMsg > HeadParamsMsgPtr;
typedef boost::shared_ptr< ::movement_msgs::HeadParamsMsg const> HeadParamsMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::HeadParamsMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::HeadParamsMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_msgs::HeadParamsMsg_<ContainerAllocator1> & lhs, const ::movement_msgs::HeadParamsMsg_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction &&
    lhs.pattern == rhs.pattern;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_msgs::HeadParamsMsg_<ContainerAllocator1> & lhs, const ::movement_msgs::HeadParamsMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::HeadParamsMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::HeadParamsMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::HeadParamsMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::HeadParamsMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::HeadParamsMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::HeadParamsMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::HeadParamsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd8add9ae07028e68b98196268fea8b1";
  }

  static const char* value(const ::movement_msgs::HeadParamsMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd8add9ae07028e6ULL;
  static const uint64_t static_value2 = 0x8b98196268fea8b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::HeadParamsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/HeadParamsMsg";
  }

  static const char* value(const ::movement_msgs::HeadParamsMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::HeadParamsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string direction\n"
"string pattern\n"
;
  }

  static const char* value(const ::movement_msgs::HeadParamsMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::HeadParamsMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.pattern);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HeadParamsMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::HeadParamsMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_msgs::HeadParamsMsg_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.direction);
    s << indent << "pattern: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pattern);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_HEADPARAMSMSG_H
