// Generated by gencpp from file movement_msgs/WalkingPositionsMsg.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_WALKINGPOSITIONSMSG_H
#define MOVEMENT_MSGS_MESSAGE_WALKINGPOSITIONSMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_msgs
{
template <class ContainerAllocator>
struct WalkingPositionsMsg_
{
  typedef WalkingPositionsMsg_<ContainerAllocator> Type;

  WalkingPositionsMsg_()
    : positions()  {
      positions.assign(0.0);
  }
  WalkingPositionsMsg_(const ContainerAllocator& _alloc)
    : positions()  {
  (void)_alloc;
      positions.assign(0.0);
  }



   typedef boost::array<double, 12>  _positions_type;
  _positions_type positions;





  typedef boost::shared_ptr< ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> const> ConstPtr;

}; // struct WalkingPositionsMsg_

typedef ::movement_msgs::WalkingPositionsMsg_<std::allocator<void> > WalkingPositionsMsg;

typedef boost::shared_ptr< ::movement_msgs::WalkingPositionsMsg > WalkingPositionsMsgPtr;
typedef boost::shared_ptr< ::movement_msgs::WalkingPositionsMsg const> WalkingPositionsMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator1> & lhs, const ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator2> & rhs)
{
  return lhs.positions == rhs.positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator1> & lhs, const ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "432ba4694a7ccfad78b66057edbee5ed";
  }

  static const char* value(const ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x432ba4694a7ccfadULL;
  static const uint64_t static_value2 = 0x78b66057edbee5edULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/WalkingPositionsMsg";
  }

  static const char* value(const ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[12] positions\n"
;
  }

  static const char* value(const ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WalkingPositionsMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_msgs::WalkingPositionsMsg_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_WALKINGPOSITIONSMSG_H
