// Generated by gencpp from file movement_msgs/WalkTestParametersSrv.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_WALKTESTPARAMETERSSRV_H
#define MOVEMENT_MSGS_MESSAGE_WALKTESTPARAMETERSSRV_H

#include <ros/service_traits.h>


#include <movement_msgs/WalkTestParametersSrvRequest.h>
#include <movement_msgs/WalkTestParametersSrvResponse.h>


namespace movement_msgs
{

struct WalkTestParametersSrv
{

typedef WalkTestParametersSrvRequest Request;
typedef WalkTestParametersSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WalkTestParametersSrv
} // namespace movement_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_msgs::WalkTestParametersSrv > {
  static const char* value()
  {
    return "7113a794fe0bdf7ad1da5428852cd6a2";
  }

  static const char* value(const ::movement_msgs::WalkTestParametersSrv&) { return value(); }
};

template<>
struct DataType< ::movement_msgs::WalkTestParametersSrv > {
  static const char* value()
  {
    return "movement_msgs/WalkTestParametersSrv";
  }

  static const char* value(const ::movement_msgs::WalkTestParametersSrv&) { return value(); }
};


// service_traits::MD5Sum< ::movement_msgs::WalkTestParametersSrvRequest> should match
// service_traits::MD5Sum< ::movement_msgs::WalkTestParametersSrv >
template<>
struct MD5Sum< ::movement_msgs::WalkTestParametersSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_msgs::WalkTestParametersSrv >::value();
  }
  static const char* value(const ::movement_msgs::WalkTestParametersSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_msgs::WalkTestParametersSrvRequest> should match
// service_traits::DataType< ::movement_msgs::WalkTestParametersSrv >
template<>
struct DataType< ::movement_msgs::WalkTestParametersSrvRequest>
{
  static const char* value()
  {
    return DataType< ::movement_msgs::WalkTestParametersSrv >::value();
  }
  static const char* value(const ::movement_msgs::WalkTestParametersSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_msgs::WalkTestParametersSrvResponse> should match
// service_traits::MD5Sum< ::movement_msgs::WalkTestParametersSrv >
template<>
struct MD5Sum< ::movement_msgs::WalkTestParametersSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_msgs::WalkTestParametersSrv >::value();
  }
  static const char* value(const ::movement_msgs::WalkTestParametersSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_msgs::WalkTestParametersSrvResponse> should match
// service_traits::DataType< ::movement_msgs::WalkTestParametersSrv >
template<>
struct DataType< ::movement_msgs::WalkTestParametersSrvResponse>
{
  static const char* value()
  {
    return DataType< ::movement_msgs::WalkTestParametersSrv >::value();
  }
  static const char* value(const ::movement_msgs::WalkTestParametersSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_WALKTESTPARAMETERSSRV_H
