// Generated by gencpp from file movement_msgs/WebotsRequestMsg.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_WEBOTSREQUESTMSG_H
#define MOVEMENT_MSGS_MESSAGE_WEBOTSREQUESTMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_msgs
{
template <class ContainerAllocator>
struct WebotsRequestMsg_
{
  typedef WebotsRequestMsg_<ContainerAllocator> Type;

  WebotsRequestMsg_()
    : motors_position()
    , motors_velocity()  {
      motors_position.assign(0.0);

      motors_velocity.assign(0.0);
  }
  WebotsRequestMsg_(const ContainerAllocator& _alloc)
    : motors_position()
    , motors_velocity()  {
  (void)_alloc;
      motors_position.assign(0.0);

      motors_velocity.assign(0.0);
  }



   typedef boost::array<float, 20>  _motors_position_type;
  _motors_position_type motors_position;

   typedef boost::array<float, 20>  _motors_velocity_type;
  _motors_velocity_type motors_velocity;





  typedef boost::shared_ptr< ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> const> ConstPtr;

}; // struct WebotsRequestMsg_

typedef ::movement_msgs::WebotsRequestMsg_<std::allocator<void> > WebotsRequestMsg;

typedef boost::shared_ptr< ::movement_msgs::WebotsRequestMsg > WebotsRequestMsgPtr;
typedef boost::shared_ptr< ::movement_msgs::WebotsRequestMsg const> WebotsRequestMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_msgs::WebotsRequestMsg_<ContainerAllocator1> & lhs, const ::movement_msgs::WebotsRequestMsg_<ContainerAllocator2> & rhs)
{
  return lhs.motors_position == rhs.motors_position &&
    lhs.motors_velocity == rhs.motors_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_msgs::WebotsRequestMsg_<ContainerAllocator1> & lhs, const ::movement_msgs::WebotsRequestMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3463d5e3ddb49315fab6bfa4cde9cb44";
  }

  static const char* value(const ::movement_msgs::WebotsRequestMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3463d5e3ddb49315ULL;
  static const uint64_t static_value2 = 0xfab6bfa4cde9cb44ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/WebotsRequestMsg";
  }

  static const char* value(const ::movement_msgs::WebotsRequestMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[20] motors_position\n"
"float32[20] motors_velocity\n"
;
  }

  static const char* value(const ::movement_msgs::WebotsRequestMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motors_position);
      stream.next(m.motors_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WebotsRequestMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::WebotsRequestMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_msgs::WebotsRequestMsg_<ContainerAllocator>& v)
  {
    s << indent << "motors_position[]" << std::endl;
    for (size_t i = 0; i < v.motors_position.size(); ++i)
    {
      s << indent << "  motors_position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.motors_position[i]);
    }
    s << indent << "motors_velocity[]" << std::endl;
    for (size_t i = 0; i < v.motors_velocity.size(); ++i)
    {
      s << indent << "  motors_velocity[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.motors_velocity[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_WEBOTSREQUESTMSG_H
