// Generated by gencpp from file movement_utils/balanceRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_BALANCEREQUEST_H
#define MOVEMENT_UTILS_MESSAGE_BALANCEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_utils
{
template <class ContainerAllocator>
struct balanceRequest_
{
  typedef balanceRequest_<ContainerAllocator> Type;

  balanceRequest_()
    : supported_foot(0)  {
    }
  balanceRequest_(const ContainerAllocator& _alloc)
    : supported_foot(0)  {
  (void)_alloc;
    }



   typedef int8_t _supported_foot_type;
  _supported_foot_type supported_foot;





  typedef boost::shared_ptr< ::movement_utils::balanceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_utils::balanceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct balanceRequest_

typedef ::movement_utils::balanceRequest_<std::allocator<void> > balanceRequest;

typedef boost::shared_ptr< ::movement_utils::balanceRequest > balanceRequestPtr;
typedef boost::shared_ptr< ::movement_utils::balanceRequest const> balanceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_utils::balanceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_utils::balanceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_utils::balanceRequest_<ContainerAllocator1> & lhs, const ::movement_utils::balanceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.supported_foot == rhs.supported_foot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_utils::balanceRequest_<ContainerAllocator1> & lhs, const ::movement_utils::balanceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_utils::balanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_utils::balanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::balanceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::balanceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::balanceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::balanceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_utils::balanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1b5603de1f5aff37830343de911d19a";
  }

  static const char* value(const ::movement_utils::balanceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1b5603de1f5aff3ULL;
  static const uint64_t static_value2 = 0x7830343de911d19aULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_utils::balanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_utils/balanceRequest";
  }

  static const char* value(const ::movement_utils::balanceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_utils::balanceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 supported_foot\n"
"\n"
;
  }

  static const char* value(const ::movement_utils::balanceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_utils::balanceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.supported_foot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct balanceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_utils::balanceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_utils::balanceRequest_<ContainerAllocator>& v)
  {
    s << indent << "supported_foot: ";
    Printer<int8_t>::stream(s, indent + "  ", v.supported_foot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_BALANCEREQUEST_H
