// Generated by gencpp from file movement_utils/balance.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_BALANCE_H
#define MOVEMENT_UTILS_MESSAGE_BALANCE_H

#include <ros/service_traits.h>


#include <movement_utils/balanceRequest.h>
#include <movement_utils/balanceResponse.h>


namespace movement_utils
{

struct balance
{

typedef balanceRequest Request;
typedef balanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct balance
} // namespace movement_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_utils::balance > {
  static const char* value()
  {
    return "01c548ad4bcd6f9d88f95b8adc185129";
  }

  static const char* value(const ::movement_utils::balance&) { return value(); }
};

template<>
struct DataType< ::movement_utils::balance > {
  static const char* value()
  {
    return "movement_utils/balance";
  }

  static const char* value(const ::movement_utils::balance&) { return value(); }
};


// service_traits::MD5Sum< ::movement_utils::balanceRequest> should match
// service_traits::MD5Sum< ::movement_utils::balance >
template<>
struct MD5Sum< ::movement_utils::balanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::balance >::value();
  }
  static const char* value(const ::movement_utils::balanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::balanceRequest> should match
// service_traits::DataType< ::movement_utils::balance >
template<>
struct DataType< ::movement_utils::balanceRequest>
{
  static const char* value()
  {
    return DataType< ::movement_utils::balance >::value();
  }
  static const char* value(const ::movement_utils::balanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_utils::balanceResponse> should match
// service_traits::MD5Sum< ::movement_utils::balance >
template<>
struct MD5Sum< ::movement_utils::balanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::balance >::value();
  }
  static const char* value(const ::movement_utils::balanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::balanceResponse> should match
// service_traits::DataType< ::movement_utils::balance >
template<>
struct DataType< ::movement_utils::balanceResponse>
{
  static const char* value()
  {
    return DataType< ::movement_utils::balance >::value();
  }
  static const char* value(const ::movement_utils::balanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_BALANCE_H
