// Generated by gencpp from file movement_utils/body_feedback.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_BODY_FEEDBACK_H
#define MOVEMENT_UTILS_MESSAGE_BODY_FEEDBACK_H

#include <ros/service_traits.h>


#include <movement_utils/body_feedbackRequest.h>
#include <movement_utils/body_feedbackResponse.h>


namespace movement_utils
{

struct body_feedback
{

typedef body_feedbackRequest Request;
typedef body_feedbackResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct body_feedback
} // namespace movement_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_utils::body_feedback > {
  static const char* value()
  {
    return "1e559a2e011119a9aa759d0e8a946d1f";
  }

  static const char* value(const ::movement_utils::body_feedback&) { return value(); }
};

template<>
struct DataType< ::movement_utils::body_feedback > {
  static const char* value()
  {
    return "movement_utils/body_feedback";
  }

  static const char* value(const ::movement_utils::body_feedback&) { return value(); }
};


// service_traits::MD5Sum< ::movement_utils::body_feedbackRequest> should match
// service_traits::MD5Sum< ::movement_utils::body_feedback >
template<>
struct MD5Sum< ::movement_utils::body_feedbackRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::body_feedback >::value();
  }
  static const char* value(const ::movement_utils::body_feedbackRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::body_feedbackRequest> should match
// service_traits::DataType< ::movement_utils::body_feedback >
template<>
struct DataType< ::movement_utils::body_feedbackRequest>
{
  static const char* value()
  {
    return DataType< ::movement_utils::body_feedback >::value();
  }
  static const char* value(const ::movement_utils::body_feedbackRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_utils::body_feedbackResponse> should match
// service_traits::MD5Sum< ::movement_utils::body_feedback >
template<>
struct MD5Sum< ::movement_utils::body_feedbackResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::body_feedback >::value();
  }
  static const char* value(const ::movement_utils::body_feedbackResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::body_feedbackResponse> should match
// service_traits::DataType< ::movement_utils::body_feedback >
template<>
struct DataType< ::movement_utils::body_feedbackResponse>
{
  static const char* value()
  {
    return DataType< ::movement_utils::body_feedback >::value();
  }
  static const char* value(const ::movement_utils::body_feedbackResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_BODY_FEEDBACK_H
