// Generated by gencpp from file movement_utils/body_feedbackRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_BODY_FEEDBACKREQUEST_H
#define MOVEMENT_UTILS_MESSAGE_BODY_FEEDBACKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_utils
{
template <class ContainerAllocator>
struct body_feedbackRequest_
{
  typedef body_feedbackRequest_<ContainerAllocator> Type;

  body_feedbackRequest_()
    : dont_use(false)  {
    }
  body_feedbackRequest_(const ContainerAllocator& _alloc)
    : dont_use(false)  {
  (void)_alloc;
    }



   typedef uint8_t _dont_use_type;
  _dont_use_type dont_use;





  typedef boost::shared_ptr< ::movement_utils::body_feedbackRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_utils::body_feedbackRequest_<ContainerAllocator> const> ConstPtr;

}; // struct body_feedbackRequest_

typedef ::movement_utils::body_feedbackRequest_<std::allocator<void> > body_feedbackRequest;

typedef boost::shared_ptr< ::movement_utils::body_feedbackRequest > body_feedbackRequestPtr;
typedef boost::shared_ptr< ::movement_utils::body_feedbackRequest const> body_feedbackRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_utils::body_feedbackRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_utils::body_feedbackRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_utils::body_feedbackRequest_<ContainerAllocator1> & lhs, const ::movement_utils::body_feedbackRequest_<ContainerAllocator2> & rhs)
{
  return lhs.dont_use == rhs.dont_use;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_utils::body_feedbackRequest_<ContainerAllocator1> & lhs, const ::movement_utils::body_feedbackRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_utils::body_feedbackRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_utils::body_feedbackRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::body_feedbackRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::body_feedbackRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::body_feedbackRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::body_feedbackRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_utils::body_feedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e681e4699d32e2108cfd7b961bdbeafa";
  }

  static const char* value(const ::movement_utils::body_feedbackRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe681e4699d32e210ULL;
  static const uint64_t static_value2 = 0x8cfd7b961bdbeafaULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_utils::body_feedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_utils/body_feedbackRequest";
  }

  static const char* value(const ::movement_utils::body_feedbackRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_utils::body_feedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool dont_use\n"
;
  }

  static const char* value(const ::movement_utils::body_feedbackRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_utils::body_feedbackRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dont_use);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct body_feedbackRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_utils::body_feedbackRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_utils::body_feedbackRequest_<ContainerAllocator>& v)
  {
    s << indent << "dont_use: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dont_use);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_BODY_FEEDBACKREQUEST_H
