// Generated by gencpp from file movement_utils/enable_torque.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_ENABLE_TORQUE_H
#define MOVEMENT_UTILS_MESSAGE_ENABLE_TORQUE_H

#include <ros/service_traits.h>


#include <movement_utils/enable_torqueRequest.h>
#include <movement_utils/enable_torqueResponse.h>


namespace movement_utils
{

struct enable_torque
{

typedef enable_torqueRequest Request;
typedef enable_torqueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct enable_torque
} // namespace movement_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_utils::enable_torque > {
  static const char* value()
  {
    return "56c16441f9caa9412e348ec2e61432df";
  }

  static const char* value(const ::movement_utils::enable_torque&) { return value(); }
};

template<>
struct DataType< ::movement_utils::enable_torque > {
  static const char* value()
  {
    return "movement_utils/enable_torque";
  }

  static const char* value(const ::movement_utils::enable_torque&) { return value(); }
};


// service_traits::MD5Sum< ::movement_utils::enable_torqueRequest> should match
// service_traits::MD5Sum< ::movement_utils::enable_torque >
template<>
struct MD5Sum< ::movement_utils::enable_torqueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::enable_torque >::value();
  }
  static const char* value(const ::movement_utils::enable_torqueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::enable_torqueRequest> should match
// service_traits::DataType< ::movement_utils::enable_torque >
template<>
struct DataType< ::movement_utils::enable_torqueRequest>
{
  static const char* value()
  {
    return DataType< ::movement_utils::enable_torque >::value();
  }
  static const char* value(const ::movement_utils::enable_torqueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_utils::enable_torqueResponse> should match
// service_traits::MD5Sum< ::movement_utils::enable_torque >
template<>
struct MD5Sum< ::movement_utils::enable_torqueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::enable_torque >::value();
  }
  static const char* value(const ::movement_utils::enable_torqueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::enable_torqueResponse> should match
// service_traits::DataType< ::movement_utils::enable_torque >
template<>
struct DataType< ::movement_utils::enable_torqueResponse>
{
  static const char* value()
  {
    return DataType< ::movement_utils::enable_torque >::value();
  }
  static const char* value(const ::movement_utils::enable_torqueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_ENABLE_TORQUE_H
