// Generated by gencpp from file movement_utils/enable_torqueRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_ENABLE_TORQUEREQUEST_H
#define MOVEMENT_UTILS_MESSAGE_ENABLE_TORQUEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_utils
{
template <class ContainerAllocator>
struct enable_torqueRequest_
{
  typedef enable_torqueRequest_<ContainerAllocator> Type;

  enable_torqueRequest_()
    : data(false)
    , motor_ids()  {
    }
  enable_torqueRequest_(const ContainerAllocator& _alloc)
    : data(false)
    , motor_ids(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _motor_ids_type;
  _motor_ids_type motor_ids;





  typedef boost::shared_ptr< ::movement_utils::enable_torqueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_utils::enable_torqueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct enable_torqueRequest_

typedef ::movement_utils::enable_torqueRequest_<std::allocator<void> > enable_torqueRequest;

typedef boost::shared_ptr< ::movement_utils::enable_torqueRequest > enable_torqueRequestPtr;
typedef boost::shared_ptr< ::movement_utils::enable_torqueRequest const> enable_torqueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_utils::enable_torqueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_utils::enable_torqueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_utils::enable_torqueRequest_<ContainerAllocator1> & lhs, const ::movement_utils::enable_torqueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.motor_ids == rhs.motor_ids;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_utils::enable_torqueRequest_<ContainerAllocator1> & lhs, const ::movement_utils::enable_torqueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_utils::enable_torqueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_utils::enable_torqueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::enable_torqueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::enable_torqueRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::enable_torqueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::enable_torqueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_utils::enable_torqueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "370ba162233787ced723089d2219a1fa";
  }

  static const char* value(const ::movement_utils::enable_torqueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x370ba162233787ceULL;
  static const uint64_t static_value2 = 0xd723089d2219a1faULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_utils::enable_torqueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_utils/enable_torqueRequest";
  }

  static const char* value(const ::movement_utils::enable_torqueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_utils::enable_torqueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool data\n"
"int8[] motor_ids\n"
;
  }

  static const char* value(const ::movement_utils::enable_torqueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_utils::enable_torqueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.motor_ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct enable_torqueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_utils::enable_torqueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_utils::enable_torqueRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
    s << indent << "motor_ids[]" << std::endl;
    for (size_t i = 0; i < v.motor_ids.size(); ++i)
    {
      s << indent << "  motor_ids[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.motor_ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_ENABLE_TORQUEREQUEST_H
