// Generated by gencpp from file movement_utils/gaitRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_GAITREQUEST_H
#define MOVEMENT_UTILS_MESSAGE_GAITREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_utils
{
template <class ContainerAllocator>
struct gaitRequest_
{
  typedef gaitRequest_<ContainerAllocator> Type;

  gaitRequest_()
    : steps_number(0)
    , step_height(0.0)  {
    }
  gaitRequest_(const ContainerAllocator& _alloc)
    : steps_number(0)
    , step_height(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _steps_number_type;
  _steps_number_type steps_number;

   typedef float _step_height_type;
  _step_height_type step_height;





  typedef boost::shared_ptr< ::movement_utils::gaitRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_utils::gaitRequest_<ContainerAllocator> const> ConstPtr;

}; // struct gaitRequest_

typedef ::movement_utils::gaitRequest_<std::allocator<void> > gaitRequest;

typedef boost::shared_ptr< ::movement_utils::gaitRequest > gaitRequestPtr;
typedef boost::shared_ptr< ::movement_utils::gaitRequest const> gaitRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_utils::gaitRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_utils::gaitRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_utils::gaitRequest_<ContainerAllocator1> & lhs, const ::movement_utils::gaitRequest_<ContainerAllocator2> & rhs)
{
  return lhs.steps_number == rhs.steps_number &&
    lhs.step_height == rhs.step_height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_utils::gaitRequest_<ContainerAllocator1> & lhs, const ::movement_utils::gaitRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_utils::gaitRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_utils::gaitRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::gaitRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::gaitRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::gaitRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::gaitRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_utils::gaitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80c470ae217144d053d06dd858989a2f";
  }

  static const char* value(const ::movement_utils::gaitRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80c470ae217144d0ULL;
  static const uint64_t static_value2 = 0x53d06dd858989a2fULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_utils::gaitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_utils/gaitRequest";
  }

  static const char* value(const ::movement_utils::gaitRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_utils::gaitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 steps_number\n"
"float32 step_height\n"
;
  }

  static const char* value(const ::movement_utils::gaitRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_utils::gaitRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steps_number);
      stream.next(m.step_height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gaitRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_utils::gaitRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_utils::gaitRequest_<ContainerAllocator>& v)
  {
    s << indent << "steps_number: ";
    Printer<int8_t>::stream(s, indent + "  ", v.steps_number);
    s << indent << "step_height: ";
    Printer<float>::stream(s, indent + "  ", v.step_height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_GAITREQUEST_H
