// Generated by gencpp from file movement_utils/gait.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_GAIT_H
#define MOVEMENT_UTILS_MESSAGE_GAIT_H

#include <ros/service_traits.h>


#include <movement_utils/gaitRequest.h>
#include <movement_utils/gaitResponse.h>


namespace movement_utils
{

struct gait
{

typedef gaitRequest Request;
typedef gaitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gait
} // namespace movement_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_utils::gait > {
  static const char* value()
  {
    return "372f208eec6910dde42b51ee38202481";
  }

  static const char* value(const ::movement_utils::gait&) { return value(); }
};

template<>
struct DataType< ::movement_utils::gait > {
  static const char* value()
  {
    return "movement_utils/gait";
  }

  static const char* value(const ::movement_utils::gait&) { return value(); }
};


// service_traits::MD5Sum< ::movement_utils::gaitRequest> should match
// service_traits::MD5Sum< ::movement_utils::gait >
template<>
struct MD5Sum< ::movement_utils::gaitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::gait >::value();
  }
  static const char* value(const ::movement_utils::gaitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::gaitRequest> should match
// service_traits::DataType< ::movement_utils::gait >
template<>
struct DataType< ::movement_utils::gaitRequest>
{
  static const char* value()
  {
    return DataType< ::movement_utils::gait >::value();
  }
  static const char* value(const ::movement_utils::gaitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_utils::gaitResponse> should match
// service_traits::MD5Sum< ::movement_utils::gait >
template<>
struct MD5Sum< ::movement_utils::gaitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::gait >::value();
  }
  static const char* value(const ::movement_utils::gaitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::gaitResponse> should match
// service_traits::DataType< ::movement_utils::gait >
template<>
struct DataType< ::movement_utils::gaitResponse>
{
  static const char* value()
  {
    return DataType< ::movement_utils::gait >::value();
  }
  static const char* value(const ::movement_utils::gaitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_GAIT_H
