// Generated by gencpp from file movement_utils/head_feedback.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_HEAD_FEEDBACK_H
#define MOVEMENT_UTILS_MESSAGE_HEAD_FEEDBACK_H

#include <ros/service_traits.h>


#include <movement_utils/head_feedbackRequest.h>
#include <movement_utils/head_feedbackResponse.h>


namespace movement_utils
{

struct head_feedback
{

typedef head_feedbackRequest Request;
typedef head_feedbackResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct head_feedback
} // namespace movement_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_utils::head_feedback > {
  static const char* value()
  {
    return "a254b821d70340d5ccc8779b3f5e7d9c";
  }

  static const char* value(const ::movement_utils::head_feedback&) { return value(); }
};

template<>
struct DataType< ::movement_utils::head_feedback > {
  static const char* value()
  {
    return "movement_utils/head_feedback";
  }

  static const char* value(const ::movement_utils::head_feedback&) { return value(); }
};


// service_traits::MD5Sum< ::movement_utils::head_feedbackRequest> should match
// service_traits::MD5Sum< ::movement_utils::head_feedback >
template<>
struct MD5Sum< ::movement_utils::head_feedbackRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::head_feedback >::value();
  }
  static const char* value(const ::movement_utils::head_feedbackRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::head_feedbackRequest> should match
// service_traits::DataType< ::movement_utils::head_feedback >
template<>
struct DataType< ::movement_utils::head_feedbackRequest>
{
  static const char* value()
  {
    return DataType< ::movement_utils::head_feedback >::value();
  }
  static const char* value(const ::movement_utils::head_feedbackRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_utils::head_feedbackResponse> should match
// service_traits::MD5Sum< ::movement_utils::head_feedback >
template<>
struct MD5Sum< ::movement_utils::head_feedbackResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::head_feedback >::value();
  }
  static const char* value(const ::movement_utils::head_feedbackResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::head_feedbackResponse> should match
// service_traits::DataType< ::movement_utils::head_feedback >
template<>
struct DataType< ::movement_utils::head_feedbackResponse>
{
  static const char* value()
  {
    return DataType< ::movement_utils::head_feedback >::value();
  }
  static const char* value(const ::movement_utils::head_feedbackResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_HEAD_FEEDBACK_H
