// Generated by gencpp from file movement_utils/head_motors_data.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_HEAD_MOTORS_DATA_H
#define MOVEMENT_UTILS_MESSAGE_HEAD_MOTORS_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_utils
{
template <class ContainerAllocator>
struct head_motors_data_
{
  typedef head_motors_data_<ContainerAllocator> Type;

  head_motors_data_()
    : pos_vector()  {
      pos_vector.assign(0.0);
  }
  head_motors_data_(const ContainerAllocator& _alloc)
    : pos_vector()  {
  (void)_alloc;
      pos_vector.assign(0.0);
  }



   typedef boost::array<float, 2>  _pos_vector_type;
  _pos_vector_type pos_vector;





  typedef boost::shared_ptr< ::movement_utils::head_motors_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_utils::head_motors_data_<ContainerAllocator> const> ConstPtr;

}; // struct head_motors_data_

typedef ::movement_utils::head_motors_data_<std::allocator<void> > head_motors_data;

typedef boost::shared_ptr< ::movement_utils::head_motors_data > head_motors_dataPtr;
typedef boost::shared_ptr< ::movement_utils::head_motors_data const> head_motors_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_utils::head_motors_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_utils::head_motors_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_utils::head_motors_data_<ContainerAllocator1> & lhs, const ::movement_utils::head_motors_data_<ContainerAllocator2> & rhs)
{
  return lhs.pos_vector == rhs.pos_vector;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_utils::head_motors_data_<ContainerAllocator1> & lhs, const ::movement_utils::head_motors_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_utils::head_motors_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_utils::head_motors_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::head_motors_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::head_motors_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::head_motors_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::head_motors_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_utils::head_motors_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "019f44c03fbd0840875f997c96bee773";
  }

  static const char* value(const ::movement_utils::head_motors_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x019f44c03fbd0840ULL;
  static const uint64_t static_value2 = 0x875f997c96bee773ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_utils::head_motors_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_utils/head_motors_data";
  }

  static const char* value(const ::movement_utils::head_motors_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_utils::head_motors_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[2] pos_vector\n"
;
  }

  static const char* value(const ::movement_utils::head_motors_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_utils::head_motors_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_vector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct head_motors_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_utils::head_motors_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_utils::head_motors_data_<ContainerAllocator>& v)
  {
    s << indent << "pos_vector[]" << std::endl;
    for (size_t i = 0; i < v.pos_vector.size(); ++i)
    {
      s << indent << "  pos_vector[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos_vector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_HEAD_MOTORS_DATA_H
