// Generated by gencpp from file movement_utils/pageRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_PAGEREQUEST_H
#define MOVEMENT_UTILS_MESSAGE_PAGEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_utils
{
template <class ContainerAllocator>
struct pageRequest_
{
  typedef pageRequest_<ContainerAllocator> Type;

  pageRequest_()
    : page_name()  {
    }
  pageRequest_(const ContainerAllocator& _alloc)
    : page_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _page_name_type;
  _page_name_type page_name;





  typedef boost::shared_ptr< ::movement_utils::pageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_utils::pageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pageRequest_

typedef ::movement_utils::pageRequest_<std::allocator<void> > pageRequest;

typedef boost::shared_ptr< ::movement_utils::pageRequest > pageRequestPtr;
typedef boost::shared_ptr< ::movement_utils::pageRequest const> pageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_utils::pageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_utils::pageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_utils::pageRequest_<ContainerAllocator1> & lhs, const ::movement_utils::pageRequest_<ContainerAllocator2> & rhs)
{
  return lhs.page_name == rhs.page_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_utils::pageRequest_<ContainerAllocator1> & lhs, const ::movement_utils::pageRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_utils::pageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_utils::pageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::pageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::pageRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::pageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::pageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_utils::pageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40ecf3e17c0163e1c8107dcfe6d53de1";
  }

  static const char* value(const ::movement_utils::pageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40ecf3e17c0163e1ULL;
  static const uint64_t static_value2 = 0xc8107dcfe6d53de1ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_utils::pageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_utils/pageRequest";
  }

  static const char* value(const ::movement_utils::pageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_utils::pageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string page_name\n"
;
  }

  static const char* value(const ::movement_utils::pageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_utils::pageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.page_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_utils::pageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_utils::pageRequest_<ContainerAllocator>& v)
  {
    s << indent << "page_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.page_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_PAGEREQUEST_H
