// Generated by gencpp from file movement_utils/page.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_PAGE_H
#define MOVEMENT_UTILS_MESSAGE_PAGE_H

#include <ros/service_traits.h>


#include <movement_utils/pageRequest.h>
#include <movement_utils/pageResponse.h>


namespace movement_utils
{

struct page
{

typedef pageRequest Request;
typedef pageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct page
} // namespace movement_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_utils::page > {
  static const char* value()
  {
    return "4f331e5d3a60dd4df8ef3fcaed28acb9";
  }

  static const char* value(const ::movement_utils::page&) { return value(); }
};

template<>
struct DataType< ::movement_utils::page > {
  static const char* value()
  {
    return "movement_utils/page";
  }

  static const char* value(const ::movement_utils::page&) { return value(); }
};


// service_traits::MD5Sum< ::movement_utils::pageRequest> should match
// service_traits::MD5Sum< ::movement_utils::page >
template<>
struct MD5Sum< ::movement_utils::pageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::page >::value();
  }
  static const char* value(const ::movement_utils::pageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::pageRequest> should match
// service_traits::DataType< ::movement_utils::page >
template<>
struct DataType< ::movement_utils::pageRequest>
{
  static const char* value()
  {
    return DataType< ::movement_utils::page >::value();
  }
  static const char* value(const ::movement_utils::pageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_utils::pageResponse> should match
// service_traits::MD5Sum< ::movement_utils::page >
template<>
struct MD5Sum< ::movement_utils::pageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::page >::value();
  }
  static const char* value(const ::movement_utils::pageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::pageResponse> should match
// service_traits::DataType< ::movement_utils::page >
template<>
struct DataType< ::movement_utils::pageResponse>
{
  static const char* value()
  {
    return DataType< ::movement_utils::page >::value();
  }
  static const char* value(const ::movement_utils::pageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_PAGE_H
