// Generated by gencpp from file movement_utils/rotate.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_ROTATE_H
#define MOVEMENT_UTILS_MESSAGE_ROTATE_H

#include <ros/service_traits.h>


#include <movement_utils/rotateRequest.h>
#include <movement_utils/rotateResponse.h>


namespace movement_utils
{

struct rotate
{

typedef rotateRequest Request;
typedef rotateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rotate
} // namespace movement_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_utils::rotate > {
  static const char* value()
  {
    return "4589fa56bf3a1c197ab709f13c7adc75";
  }

  static const char* value(const ::movement_utils::rotate&) { return value(); }
};

template<>
struct DataType< ::movement_utils::rotate > {
  static const char* value()
  {
    return "movement_utils/rotate";
  }

  static const char* value(const ::movement_utils::rotate&) { return value(); }
};


// service_traits::MD5Sum< ::movement_utils::rotateRequest> should match
// service_traits::MD5Sum< ::movement_utils::rotate >
template<>
struct MD5Sum< ::movement_utils::rotateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::rotate >::value();
  }
  static const char* value(const ::movement_utils::rotateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::rotateRequest> should match
// service_traits::DataType< ::movement_utils::rotate >
template<>
struct DataType< ::movement_utils::rotateRequest>
{
  static const char* value()
  {
    return DataType< ::movement_utils::rotate >::value();
  }
  static const char* value(const ::movement_utils::rotateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_utils::rotateResponse> should match
// service_traits::MD5Sum< ::movement_utils::rotate >
template<>
struct MD5Sum< ::movement_utils::rotateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::rotate >::value();
  }
  static const char* value(const ::movement_utils::rotateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::rotateResponse> should match
// service_traits::DataType< ::movement_utils::rotate >
template<>
struct DataType< ::movement_utils::rotateResponse>
{
  static const char* value()
  {
    return DataType< ::movement_utils::rotate >::value();
  }
  static const char* value(const ::movement_utils::rotateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_ROTATE_H
