// Generated by gencpp from file movement_utils/rotateRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_ROTATEREQUEST_H
#define MOVEMENT_UTILS_MESSAGE_ROTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_utils
{
template <class ContainerAllocator>
struct rotateRequest_
{
  typedef rotateRequest_<ContainerAllocator> Type;

  rotateRequest_()
    : direction(0)
    , steps_number(0)  {
    }
  rotateRequest_(const ContainerAllocator& _alloc)
    : direction(0)
    , steps_number(0)  {
  (void)_alloc;
    }



   typedef int8_t _direction_type;
  _direction_type direction;

   typedef int8_t _steps_number_type;
  _steps_number_type steps_number;





  typedef boost::shared_ptr< ::movement_utils::rotateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_utils::rotateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct rotateRequest_

typedef ::movement_utils::rotateRequest_<std::allocator<void> > rotateRequest;

typedef boost::shared_ptr< ::movement_utils::rotateRequest > rotateRequestPtr;
typedef boost::shared_ptr< ::movement_utils::rotateRequest const> rotateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_utils::rotateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_utils::rotateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_utils::rotateRequest_<ContainerAllocator1> & lhs, const ::movement_utils::rotateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction &&
    lhs.steps_number == rhs.steps_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_utils::rotateRequest_<ContainerAllocator1> & lhs, const ::movement_utils::rotateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_utils::rotateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_utils::rotateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::rotateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::rotateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::rotateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::rotateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_utils::rotateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a9a8c34a07a44c57e5446efb205f456";
  }

  static const char* value(const ::movement_utils::rotateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a9a8c34a07a44c5ULL;
  static const uint64_t static_value2 = 0x7e5446efb205f456ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_utils::rotateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_utils/rotateRequest";
  }

  static const char* value(const ::movement_utils::rotateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_utils::rotateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 direction\n"
"int8 steps_number\n"
;
  }

  static const char* value(const ::movement_utils::rotateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_utils::rotateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.steps_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rotateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_utils::rotateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_utils::rotateRequest_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<int8_t>::stream(s, indent + "  ", v.direction);
    s << indent << "steps_number: ";
    Printer<int8_t>::stream(s, indent + "  ", v.steps_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_ROTATEREQUEST_H
