// Generated by gencpp from file movement_utils/vx.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_VX_H
#define MOVEMENT_UTILS_MESSAGE_VX_H

#include <ros/service_traits.h>


#include <movement_utils/vxRequest.h>
#include <movement_utils/vxResponse.h>


namespace movement_utils
{

struct vx
{

typedef vxRequest Request;
typedef vxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct vx
} // namespace movement_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_utils::vx > {
  static const char* value()
  {
    return "fc98f3eaa33f7560afd31582a184e752";
  }

  static const char* value(const ::movement_utils::vx&) { return value(); }
};

template<>
struct DataType< ::movement_utils::vx > {
  static const char* value()
  {
    return "movement_utils/vx";
  }

  static const char* value(const ::movement_utils::vx&) { return value(); }
};


// service_traits::MD5Sum< ::movement_utils::vxRequest> should match
// service_traits::MD5Sum< ::movement_utils::vx >
template<>
struct MD5Sum< ::movement_utils::vxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::vx >::value();
  }
  static const char* value(const ::movement_utils::vxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::vxRequest> should match
// service_traits::DataType< ::movement_utils::vx >
template<>
struct DataType< ::movement_utils::vxRequest>
{
  static const char* value()
  {
    return DataType< ::movement_utils::vx >::value();
  }
  static const char* value(const ::movement_utils::vxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_utils::vxResponse> should match
// service_traits::MD5Sum< ::movement_utils::vx >
template<>
struct MD5Sum< ::movement_utils::vxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::vx >::value();
  }
  static const char* value(const ::movement_utils::vxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::vxResponse> should match
// service_traits::DataType< ::movement_utils::vx >
template<>
struct DataType< ::movement_utils::vxResponse>
{
  static const char* value()
  {
    return DataType< ::movement_utils::vx >::value();
  }
  static const char* value(const ::movement_utils::vxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_VX_H
