// Generated by gencpp from file movement_utils/vxRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_VXREQUEST_H
#define MOVEMENT_UTILS_MESSAGE_VXREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_utils
{
template <class ContainerAllocator>
struct vxRequest_
{
  typedef vxRequest_<ContainerAllocator> Type;

  vxRequest_()
    : vx(0.0)
    , distX(0.0)  {
    }
  vxRequest_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , distX(0.0)  {
  (void)_alloc;
    }



   typedef float _vx_type;
  _vx_type vx;

   typedef float _distX_type;
  _distX_type distX;





  typedef boost::shared_ptr< ::movement_utils::vxRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_utils::vxRequest_<ContainerAllocator> const> ConstPtr;

}; // struct vxRequest_

typedef ::movement_utils::vxRequest_<std::allocator<void> > vxRequest;

typedef boost::shared_ptr< ::movement_utils::vxRequest > vxRequestPtr;
typedef boost::shared_ptr< ::movement_utils::vxRequest const> vxRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_utils::vxRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_utils::vxRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_utils::vxRequest_<ContainerAllocator1> & lhs, const ::movement_utils::vxRequest_<ContainerAllocator2> & rhs)
{
  return lhs.vx == rhs.vx &&
    lhs.distX == rhs.distX;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_utils::vxRequest_<ContainerAllocator1> & lhs, const ::movement_utils::vxRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_utils::vxRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_utils::vxRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::vxRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::vxRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::vxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::vxRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_utils::vxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "951e184e14be09096952ea3692561a5b";
  }

  static const char* value(const ::movement_utils::vxRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x951e184e14be0909ULL;
  static const uint64_t static_value2 = 0x6952ea3692561a5bULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_utils::vxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_utils/vxRequest";
  }

  static const char* value(const ::movement_utils::vxRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_utils::vxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vx\n"
"float32 distX\n"
;
  }

  static const char* value(const ::movement_utils::vxRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_utils::vxRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.distX);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vxRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_utils::vxRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_utils::vxRequest_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "distX: ";
    Printer<float>::stream(s, indent + "  ", v.distX);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_VXREQUEST_H
