// Generated by gencpp from file movement_utils/walk_forwardRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_WALK_FORWARDREQUEST_H
#define MOVEMENT_UTILS_MESSAGE_WALK_FORWARDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_utils
{
template <class ContainerAllocator>
struct walk_forwardRequest_
{
  typedef walk_forwardRequest_<ContainerAllocator> Type;

  walk_forwardRequest_()
    : support_foot(0)
    , steps_number(0)  {
    }
  walk_forwardRequest_(const ContainerAllocator& _alloc)
    : support_foot(0)
    , steps_number(0)  {
  (void)_alloc;
    }



   typedef int8_t _support_foot_type;
  _support_foot_type support_foot;

   typedef int8_t _steps_number_type;
  _steps_number_type steps_number;





  typedef boost::shared_ptr< ::movement_utils::walk_forwardRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_utils::walk_forwardRequest_<ContainerAllocator> const> ConstPtr;

}; // struct walk_forwardRequest_

typedef ::movement_utils::walk_forwardRequest_<std::allocator<void> > walk_forwardRequest;

typedef boost::shared_ptr< ::movement_utils::walk_forwardRequest > walk_forwardRequestPtr;
typedef boost::shared_ptr< ::movement_utils::walk_forwardRequest const> walk_forwardRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_utils::walk_forwardRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_utils::walk_forwardRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_utils::walk_forwardRequest_<ContainerAllocator1> & lhs, const ::movement_utils::walk_forwardRequest_<ContainerAllocator2> & rhs)
{
  return lhs.support_foot == rhs.support_foot &&
    lhs.steps_number == rhs.steps_number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_utils::walk_forwardRequest_<ContainerAllocator1> & lhs, const ::movement_utils::walk_forwardRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_utils::walk_forwardRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_utils::walk_forwardRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::walk_forwardRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_utils::walk_forwardRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::walk_forwardRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_utils::walk_forwardRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_utils::walk_forwardRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0911cfa143d6da846959597e9cd226e";
  }

  static const char* value(const ::movement_utils::walk_forwardRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0911cfa143d6da8ULL;
  static const uint64_t static_value2 = 0x46959597e9cd226eULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_utils::walk_forwardRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_utils/walk_forwardRequest";
  }

  static const char* value(const ::movement_utils::walk_forwardRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_utils::walk_forwardRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 support_foot\n"
"int8 steps_number\n"
;
  }

  static const char* value(const ::movement_utils::walk_forwardRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_utils::walk_forwardRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.support_foot);
      stream.next(m.steps_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct walk_forwardRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_utils::walk_forwardRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_utils::walk_forwardRequest_<ContainerAllocator>& v)
  {
    s << indent << "support_foot: ";
    Printer<int8_t>::stream(s, indent + "  ", v.support_foot);
    s << indent << "steps_number: ";
    Printer<int8_t>::stream(s, indent + "  ", v.steps_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_WALK_FORWARDREQUEST_H
