// Generated by gencpp from file movement_utils/walk_forward.msg
// DO NOT EDIT!


#ifndef MOVEMENT_UTILS_MESSAGE_WALK_FORWARD_H
#define MOVEMENT_UTILS_MESSAGE_WALK_FORWARD_H

#include <ros/service_traits.h>


#include <movement_utils/walk_forwardRequest.h>
#include <movement_utils/walk_forwardResponse.h>


namespace movement_utils
{

struct walk_forward
{

typedef walk_forwardRequest Request;
typedef walk_forwardResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct walk_forward
} // namespace movement_utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_utils::walk_forward > {
  static const char* value()
  {
    return "4e96d691545ef71c6c6ffe49fb624ea4";
  }

  static const char* value(const ::movement_utils::walk_forward&) { return value(); }
};

template<>
struct DataType< ::movement_utils::walk_forward > {
  static const char* value()
  {
    return "movement_utils/walk_forward";
  }

  static const char* value(const ::movement_utils::walk_forward&) { return value(); }
};


// service_traits::MD5Sum< ::movement_utils::walk_forwardRequest> should match
// service_traits::MD5Sum< ::movement_utils::walk_forward >
template<>
struct MD5Sum< ::movement_utils::walk_forwardRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::walk_forward >::value();
  }
  static const char* value(const ::movement_utils::walk_forwardRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::walk_forwardRequest> should match
// service_traits::DataType< ::movement_utils::walk_forward >
template<>
struct DataType< ::movement_utils::walk_forwardRequest>
{
  static const char* value()
  {
    return DataType< ::movement_utils::walk_forward >::value();
  }
  static const char* value(const ::movement_utils::walk_forwardRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_utils::walk_forwardResponse> should match
// service_traits::MD5Sum< ::movement_utils::walk_forward >
template<>
struct MD5Sum< ::movement_utils::walk_forwardResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_utils::walk_forward >::value();
  }
  static const char* value(const ::movement_utils::walk_forwardResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_utils::walk_forwardResponse> should match
// service_traits::DataType< ::movement_utils::walk_forward >
template<>
struct DataType< ::movement_utils::walk_forwardResponse>
{
  static const char* value()
  {
    return DataType< ::movement_utils::walk_forward >::value();
  }
  static const char* value(const ::movement_utils::walk_forwardResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_UTILS_MESSAGE_WALK_FORWARD_H
