// Generated by gencpp from file vision_msgs/Objects.msg
// DO NOT EDIT!


#ifndef VISION_MSGS_MESSAGE_OBJECTS_H
#define VISION_MSGS_MESSAGE_OBJECTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vision_msgs/Ball.h>
#include <vision_msgs/Goal.h>
#include <vision_msgs/Robot.h>
#include <sensor_msgs/Image.h>

namespace vision_msgs
{
template <class ContainerAllocator>
struct Objects_
{
  typedef Objects_<ContainerAllocator> Type;

  Objects_()
    : ball()
    , goal()
    , robots()
    , image()  {
    }
  Objects_(const ContainerAllocator& _alloc)
    : ball(_alloc)
    , goal(_alloc)
    , robots(_alloc)
    , image(_alloc)  {
  (void)_alloc;
    }



   typedef  ::vision_msgs::Ball_<ContainerAllocator>  _ball_type;
  _ball_type ball;

   typedef  ::vision_msgs::Goal_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef std::vector< ::vision_msgs::Robot_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::vision_msgs::Robot_<ContainerAllocator> >> _robots_type;
  _robots_type robots;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;





  typedef boost::shared_ptr< ::vision_msgs::Objects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_msgs::Objects_<ContainerAllocator> const> ConstPtr;

}; // struct Objects_

typedef ::vision_msgs::Objects_<std::allocator<void> > Objects;

typedef boost::shared_ptr< ::vision_msgs::Objects > ObjectsPtr;
typedef boost::shared_ptr< ::vision_msgs::Objects const> ObjectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_msgs::Objects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_msgs::Objects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_msgs::Objects_<ContainerAllocator1> & lhs, const ::vision_msgs::Objects_<ContainerAllocator2> & rhs)
{
  return lhs.ball == rhs.ball &&
    lhs.goal == rhs.goal &&
    lhs.robots == rhs.robots &&
    lhs.image == rhs.image;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_msgs::Objects_<ContainerAllocator1> & lhs, const ::vision_msgs::Objects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::Objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_msgs::Objects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::Objects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_msgs::Objects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::Objects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_msgs::Objects_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_msgs::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19f71dba810720091bb37489652c025c";
  }

  static const char* value(const ::vision_msgs::Objects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19f71dba81072009ULL;
  static const uint64_t static_value2 = 0x1bb37489652c025cULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_msgs::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/Objects";
  }

  static const char* value(const ::vision_msgs::Objects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_msgs::Objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_msgs/Ball ball\n"
"vision_msgs/Goal goal\n"
"vision_msgs/Robot[] robots\n"
"sensor_msgs/Image image\n"
"================================================================================\n"
"MSG: vision_msgs/Ball\n"
"bool found\n"
"int32 x\n"
"int32 y\n"
"int32 roi_width\n"
"int32 roi_height\n"
"================================================================================\n"
"MSG: vision_msgs/Goal\n"
"bool found\n"
"int32 x\n"
"int32 y\n"
"================================================================================\n"
"MSG: vision_msgs/Robot\n"
"int32 x\n"
"int32 y\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::vision_msgs::Objects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_msgs::Objects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ball);
      stream.next(m.goal);
      stream.next(m.robots);
      stream.next(m.image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Objects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_msgs::Objects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_msgs::Objects_<ContainerAllocator>& v)
  {
    s << indent << "ball: ";
    s << std::endl;
    Printer< ::vision_msgs::Ball_<ContainerAllocator> >::stream(s, indent + "  ", v.ball);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::vision_msgs::Goal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "robots[]" << std::endl;
    for (size_t i = 0; i < v.robots.size(); ++i)
    {
      s << indent << "  robots[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vision_msgs::Robot_<ContainerAllocator> >::stream(s, indent + "    ", v.robots[i]);
    }
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MSGS_MESSAGE_OBJECTS_H
