# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SFTPG.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys, json, os
import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32MultiArray
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

MAIN_DIR = '/home/'+os.getlogin()+'/edromufu/src/movement/Ros2_change/src/tahara_pages/tahara_pages/'

class MyPublisher(Node):
    def __init__(self):
        super().__init__('pot_topic')
        self.publisher_ = self.create_publisher(Float32MultiArray, 'pot_py_topic', 10)
        self.timer = self.create_timer(1.0, self.timer_callback)  # Chama a callback a cada 1 segundo
        self.msg = Float32MultiArray()

    def timer_callback(self):
        
        self.publisher_.publish(self.msg)



rclpy.init()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 571)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(MAIN_DIR+"LogoEdrom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)

        
        self.publisher = MyPublisher()



        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AV_1 = QtWidgets.QPushButton(self.centralwidget)
        self.AV_1.setGeometry(QtCore.QRect(250, 150, 42, 36))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(MAIN_DIR+ "green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AV_1.setIcon(icon1)
        self.AV_1.setIconSize(QtCore.QSize(30, 30))
        self.AV_1.setAutoRepeat(True)
        self.AV_1.setAutoRepeatDelay(300)
        self.AV_1.setObjectName("AV_1")
        self.RT_1 = QtWidgets.QPushButton(self.centralwidget)
        self.RT_1.setGeometry(QtCore.QRect(250, 200, 42, 36))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(MAIN_DIR+"red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RT_1.setIcon(icon2)
        self.RT_1.setIconSize(QtCore.QSize(30, 30))
        self.RT_1.setAutoRepeat(True)
        self.RT_1.setObjectName("RT_1")
        self.RT_2 = QtWidgets.QPushButton(self.centralwidget)
        self.RT_2.setGeometry(QtCore.QRect(330, 200, 42, 36))
        self.RT_2.setIcon(icon2)
        self.RT_2.setIconSize(QtCore.QSize(30, 30))
        self.RT_2.setAutoRepeat(True)
        self.RT_2.setAutoExclusive(False)
        self.RT_2.setObjectName("RT_2")
        self.AV_2 = QtWidgets.QPushButton(self.centralwidget)
        self.AV_2.setGeometry(QtCore.QRect(330, 150, 42, 36))
        self.AV_2.setIcon(icon1)
        self.AV_2.setIconSize(QtCore.QSize(30, 30))
        self.AV_2.setAutoRepeat(True)
        self.AV_2.setAutoExclusive(False)
        self.AV_2.setObjectName("AV_2")
        self.RT_3 = QtWidgets.QPushButton(self.centralwidget)
        self.RT_3.setGeometry(QtCore.QRect(410, 200, 42, 36))
        self.RT_3.setIcon(icon2)
        self.RT_3.setIconSize(QtCore.QSize(30, 30))
        self.RT_3.setAutoRepeat(True)
        self.RT_3.setAutoExclusive(False)
        self.RT_3.setObjectName("RT_3")
        self.AV_3 = QtWidgets.QPushButton(self.centralwidget)
        self.AV_3.setGeometry(QtCore.QRect(410, 150, 42, 36))
        self.AV_3.setIcon(icon1)
        self.AV_3.setIconSize(QtCore.QSize(30, 30))
        self.AV_3.setAutoRepeat(True)
        self.AV_3.setAutoExclusive(False)
        self.AV_3.setObjectName("AV_3")
        self.RT_4 = QtWidgets.QPushButton(self.centralwidget)
        self.RT_4.setGeometry(QtCore.QRect(490, 200, 42, 36))
        self.RT_4.setIcon(icon2)
        self.RT_4.setIconSize(QtCore.QSize(30, 30))
        self.RT_4.setAutoRepeat(True)
        self.RT_4.setAutoExclusive(False)
        self.RT_4.setObjectName("RT_4")
        self.AV_4 = QtWidgets.QPushButton(self.centralwidget)
        self.AV_4.setGeometry(QtCore.QRect(490, 150, 42, 36))
        self.AV_4.setIcon(icon1)
        self.AV_4.setIconSize(QtCore.QSize(30, 30))
        self.AV_4.setAutoRepeat(True)
        self.AV_4.setAutoExclusive(False)
        self.AV_4.setObjectName("AV_4")
        self.RT_5 = QtWidgets.QPushButton(self.centralwidget)
        self.RT_5.setGeometry(QtCore.QRect(250, 340, 42, 36))
        self.RT_5.setIcon(icon2)
        self.RT_5.setIconSize(QtCore.QSize(30, 30))
        self.RT_5.setAutoRepeat(True)
        self.RT_5.setAutoExclusive(False)
        self.RT_5.setObjectName("RT_5")
        self.AV_5 = QtWidgets.QPushButton(self.centralwidget)
        self.AV_5.setGeometry(QtCore.QRect(250, 290, 42, 36))
        self.AV_5.setIcon(icon1)
        self.AV_5.setIconSize(QtCore.QSize(30, 30))
        self.AV_5.setAutoRepeat(True)
        self.AV_5.setAutoExclusive(False)
        self.AV_5.setObjectName("AV_5")
        self.RT_6 = QtWidgets.QPushButton(self.centralwidget)
        self.RT_6.setGeometry(QtCore.QRect(330, 340, 42, 36))
        self.RT_6.setIcon(icon2)
        self.RT_6.setIconSize(QtCore.QSize(30, 30))
        self.RT_6.setAutoRepeat(True)
        self.RT_6.setObjectName("RT_6")
        self.AV_6 = QtWidgets.QPushButton(self.centralwidget)
        self.AV_6.setGeometry(QtCore.QRect(330, 290, 42, 36))
        self.AV_6.setIcon(icon1)
        self.AV_6.setIconSize(QtCore.QSize(30, 30))
        self.AV_6.setAutoRepeat(True)
        self.AV_6.setObjectName("AV_6")
        self.RT_7 = QtWidgets.QPushButton(self.centralwidget)
        self.RT_7.setGeometry(QtCore.QRect(410, 340, 42, 36))
        self.RT_7.setIcon(icon2)
        self.RT_7.setIconSize(QtCore.QSize(30, 30))
        self.RT_7.setAutoRepeat(True)
        self.RT_7.setObjectName("RT_7")
        self.AV_7 = QtWidgets.QPushButton(self.centralwidget)
        self.AV_7.setGeometry(QtCore.QRect(410, 290, 42, 36))
        self.AV_7.setIcon(icon1)
        self.AV_7.setIconSize(QtCore.QSize(30, 30))
        self.AV_7.setAutoRepeat(True)
        self.AV_7.setObjectName("AV_7")
        self.RT_8 = QtWidgets.QPushButton(self.centralwidget)
        self.RT_8.setGeometry(QtCore.QRect(490, 340, 42, 36))
        self.RT_8.setIcon(icon2)
        self.RT_8.setIconSize(QtCore.QSize(30, 30))
        self.RT_8.setAutoRepeat(True)
        self.RT_8.setObjectName("RT_8")
        self.AV_8 = QtWidgets.QPushButton(self.centralwidget)
        self.AV_8.setGeometry(QtCore.QRect(490, 290, 42, 36))
        self.AV_8.setIcon(icon1)
        self.AV_8.setIconSize(QtCore.QSize(30, 30))
        self.AV_8.setAutoRepeat(True)
        self.AV_8.setObjectName("AV_8")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 130, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 130, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 130, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 130, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 270, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 270, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 270, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(490, 270, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")

        self.Save = QtWidgets.QPushButton(self.centralwidget)
        self.Save.setGeometry(QtCore.QRect(550, 450, 42, 36))
        self.Save.setIcon(icon1)
        self.Save.setIconSize(QtCore.QSize(30, 30))
        self.Save.setAutoRepeat(True)
        self.Save.setAutoRepeatDelay(300)
        self.Save.setObjectName("Save")
        self.savelabel = QtWidgets.QLabel(self.centralwidget)
        self.savelabel.setGeometry(QtCore.QRect(500, 450, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.savelabel.setFont(font)
        self.savelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.savelabel.setObjectName("savelabel")

        self.createJsonBut = QtWidgets.QPushButton(self.centralwidget)
        self.createJsonBut.setGeometry(QtCore.QRect(550, 50, 42, 36))
        self.createJsonBut.setIcon(icon1)
        self.createJsonBut.setIconSize(QtCore.QSize(30, 30))
        self.createJsonBut.setAutoRepeat(True)
        self.createJsonBut.setAutoRepeatDelay(300)
        self.createJsonBut.setObjectName("createJsonBut")
        self.createjsonLabel = QtWidgets.QLabel(self.centralwidget)
        self.createjsonLabel.setGeometry(QtCore.QRect(450, 50, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.createjsonLabel.setFont(font)
        self.createjsonLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.createjsonLabel.setObjectName("createjsonLabel")


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Save.clicked.connect(lambda: self.save())
        self.createJsonBut.clicked.connect(lambda: self.createJson())

        self.AV_1.clicked.connect(lambda: self.incrementar(1))
        self.AV_2.clicked.connect(lambda: self.incrementar(2))
        self.AV_3.clicked.connect(lambda: self.incrementar(3))
        self.AV_4.clicked.connect(lambda: self.incrementar(4))
        self.AV_5.clicked.connect(lambda: self.incrementar(5))
        self.AV_6.clicked.connect(lambda: self.incrementar(6))
        self.AV_7.clicked.connect(lambda: self.incrementar(7))
        self.AV_8.clicked.connect(lambda: self.incrementar(8))

        self.RT_1.clicked.connect(lambda: self.decrementar(1))
        self.RT_2.clicked.connect(lambda: self.decrementar(2))
        self.RT_3.clicked.connect(lambda: self.decrementar(3))
        self.RT_4.clicked.connect(lambda: self.decrementar(4))
        self.RT_5.clicked.connect(lambda: self.decrementar(5))
        self.RT_6.clicked.connect(lambda: self.decrementar(6))
        self.RT_7.clicked.connect(lambda: self.decrementar(7))
        self.RT_8.clicked.connect(lambda: self.decrementar(8))
    
        self.message = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
        self.fileName = None
        self.pageData = {'joints_positions': {}, 'time_between_poses': []}
        for n in range(8):
            self.pageData['joints_positions'][f'pot_{n}'] = []

            
    def incrementar(self,pos):
        self.message[pos-1] = 1.0
        self.envio()
        self.message[pos-1] = 0.0

    def decrementar(self,pos):
        self.message[pos-1] = -1.0
        self.envio()
        self.message[pos-1] = 0.0

    def envio(self):

        self.publisher.msg.data = self.message
        self.publisher.timer_callback()
            
    def save(self):

        j=0
        for i in self.pageData['joints_positions']:
            self.pageData['joints_positions'][i].append(self.message[j])
            j+=1

        print(self.pageData)

    def createJson(self):
        if self.fileName is None:
            self.fileName, _ = QFileDialog.getSaveFileName(None,"Salvar em", MAIN_DIR,"Page Files (*.json)")
            if '.json' not in self.fileName:
                self.fileName += '.json'
        with open(self.fileName, 'w') as f:
            json.dump(self.pageData,f)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sogtware de Pages - Tahara"))
        self.label.setText(_translate("MainWindow", "ANG_1"))
        self.label_2.setText(_translate("MainWindow", "ANG_2"))
        self.label_3.setText(_translate("MainWindow", "ANG_3"))
        self.label_4.setText(_translate("MainWindow", "ANG_4"))
        self.label_5.setText(_translate("MainWindow", "ANG_5"))
        self.label_6.setText(_translate("MainWindow", "ANG_6"))
        self.label_7.setText(_translate("MainWindow", "ANG_7"))
        self.label_8.setText(_translate("MainWindow", "ANG_8"))
        self.savelabel.setText(_translate("MainWindow", "Save"))
        self.createjsonLabel.setText(_translate("MainWindow", "Save in Json"))
    
    
def main():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())
 
if __name__ == '__main__':
    main()
